-- Hēlo — Ingrédients bébé seed data (0-3 ans)
-- 30 ingrédients à risque bébé : DANGER + PRÉCAUTION
-- Run schema.sql and migration-baby-mode.sql first
-- Ne pas toucher aux ingrédients existants

-- ============================================================
-- INGRÉDIENTS BÉBÉ — DANGER (15)
-- ============================================================
INSERT INTO ingredients (id, name, name_inci, synonyms, category,
  risk_level_t1, risk_level_t2, risk_level_t3, risk_level_breastfeeding, risk_level_baby,
  description_fr, source, source_url)
VALUES

('bb000001-0000-0000-0000-000000000001',
 'Phénoxyéthanol (produits bébé)',
 'Phenoxyethanol',
 ARRAY['2-Phenoxyethanol', 'Ethylene glycol monophenyl ether'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le phénoxyéthanol est un conservateur couramment utilisé dans les cosmétiques. Chez le nourrisson (moins de 3 ans), l''ANSM et l''AFSSAPS ont émis des mises en garde spécifiques : ce composé peut déprimer le système nerveux central et inhiber les réflexes de succion. Son utilisation est déconseillée dans les produits destinés aux fesses et aux zones du couche, et à proscrire dans les produits pour nourrissons de moins de 3 ans. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, AFSSAPS pédiatrique',
 'https://www.ansm.sante.fr'),

('bb000002-0000-0000-0000-000000000002',
 'MIT / Méthylisothiazolinone (bébé)',
 'Methylisothiazolinone',
 ARRAY['MIT', 'MI', '2-Methyl-4-isothiazolin-3-one', 'Methylisothiazolinone'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le MIT (méthylisothiazolinone) est un conservateur puissant interdit dans les produits cosmétiques à ne pas rincer depuis 2016 en Europe, précisément en raison du risque élevé de sensibilisation et de réaction allergique chez les jeunes enfants. Les études ont montré des effets neurotoxiques chez l''animal à des concentrations élevées. Chez le bébé dont la peau est plus perméable, ce risque est accentué. À éviter absolument dans tous les produits pour bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Règlement EU 1223/2009, SCCS, ANSM',
 'https://www.ansm.sante.fr'),

('bb000003-0000-0000-0000-000000000003',
 'Camphre (produits bébé)',
 'Camphor',
 ARRAY['2-Bornanone', 'Camphor gum', 'Camphre synthétique'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le camphre est formellement contre-indiqué chez les nourrissons et les jeunes enfants. Il peut provoquer des crises convulsives même à faibles doses, car leur système nerveux central est immature et particulièrement sensible. L''application sur la peau ou l''inhalation de vapeurs de camphre ont entraîné des cas graves d''intoxication chez les bébés. Les produits contenant du camphre (baumes, pommades, huiles) ne doivent jamais être utilisés chez l''enfant de moins de 3 ans. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Académie de Pédiatrie, Que Choisir',
 'https://www.ansm.sante.fr'),

('bb000004-0000-0000-0000-000000000004',
 'Menthol (bébé)',
 'Menthol',
 ARRAY['l-Menthol', 'peppermint crystal', 'Mint camphor', 'Mentha'],
 'cosmetic',
 'safe', 'safe', 'safe', 'caution', 'danger',
 'Le menthol est contre-indiqué chez les enfants de moins de 3 ans. Par son action sur les récepteurs TRPM8, il peut provoquer un laryngospasme ou une apnée reflexe, surtout si appliqué près du nez ou de la bouche. Des cas de détresse respiratoire ont été rapportés chez des nourrissons exposés à des produits mentholés. Les produits contenant du menthol (baumes, pommades, inhalateurs) sont à proscrire chez le bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Académie de Pédiatrie',
 'https://www.ansm.sante.fr'),

('bb000005-0000-0000-0000-000000000005',
 'Alcool éthylique (lingettes bébé)',
 'Alcohol Denat.',
 ARRAY['Ethanol', 'Denatured alcohol', 'SD Alcohol', 'Isopropanol'],
 'cosmetic',
 'caution', 'caution', 'caution', 'safe', 'danger',
 'L''alcool éthylique et l''alcool dénaturé présents dans certaines lingettes et solutions désinfectantes sont absorbés par la peau des bébés beaucoup plus facilement que chez l''adulte. La peau du nourrisson est plus fine et plus perméable. L''absorption cutanée d''alcool peut entraîner une hypoglycémie, une dépression du système nerveux central ou une acidose chez le bébé. Les lingettes pour bébé ne devraient pas contenir d''alcool. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM pédiatrique, Que Choisir',
 NULL),

('bb000006-0000-0000-0000-000000000006',
 'Parfums synthétiques forts (bébé)',
 'Parfum',
 ARRAY['Fragrance', 'Aroma', 'Perfume', 'Citral', 'Linalool', 'Eugenol'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Les parfums synthétiques forts dans les produits bébé sont une cause majeure d''allergie cutanée et d''irritation. La peau du nourrisson absorbe les molécules odorantes plus facilement. Plusieurs allergènes de parfum réglementés (linalool, citral, eugenol, limonene) sont particulièrement sensibilisants chez le jeune enfant. Le Règlement européen 2017/1410 impose l''étiquetage de 48 allergènes de parfum. Pour les bébés, il est recommandé de choisir des produits "sans parfum". Consultez votre professionnel de santé pour un avis personnalisé.',
 'Règlement EU 2017/1410, SCCS, Que Choisir',
 NULL),

('bb000007-0000-0000-0000-000000000007',
 'Parabènes (bébé)',
 'Methylparaben',
 ARRAY['Propylparaben', 'Butylparaben', 'Ethylparaben', 'Isobutylparaben', 'Isopropylparaben'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le propyl- et butylparabène sont interdits dans les cosmétiques destinés aux enfants de moins de 3 ans sur la zone du couche depuis le Règlement européen 1004/2014. Ces parabènes ont des propriétés oestrogéniques légères qui peuvent interférer avec le système endocrinien immature du nourrisson. La réglementation européenne les interdit spécifiquement pour les produits bébé en zone de couche. Évitez tout produit contenant ces parabènes pour votre bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Règlement EU 1004/2014, SCCS pédiatrique, ANSM',
 'https://www.ansm.sante.fr'),

('bb000008-0000-0000-0000-000000000008',
 'Eucalyptus (huile essentielle bébé)',
 'Eucalyptus Globulus Leaf Oil',
 ARRAY['Eucalyptol', '1,8-Cineole', 'Eucalyptus oil', 'Huile essentielle eucalyptus'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'L''huile essentielle d''eucalyptus est formellement contre-indiquée chez les enfants de moins de 7 ans selon l''ANSM et la plupart des sociétés de pédiatrie. Son principal composé actif, l''eucalyptol (1,8-cinéole), peut provoquer des convulsions et une dépression respiratoire chez les jeunes enfants. Même en faible quantité, l''inhalation ou l''application cutanée de produits à l''eucalyptus peut être dangereuse pour un bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Académie Française de Pédiatrie',
 'https://www.ansm.sante.fr'),

('bb000009-0000-0000-0000-000000000009',
 'Menthe poivrée (huile essentielle bébé)',
 'Mentha Piperita Oil',
 ARRAY['Peppermint oil', 'Mentha x piperita', 'Peppermint extract'],
 'cosmetic',
 'safe', 'safe', 'caution', 'caution', 'danger',
 'L''huile essentielle de menthe poivrée est contre-indiquée chez les enfants de moins de 7 ans. Sa forte teneur en menthol peut provoquer un laryngospasme, une bradycardie ou une apnée chez le nourrisson, même en petites quantités. L''inhalation directe ou l''application cutanée près du visage d''un bébé est particulièrement risquée. Des accidents graves ont été documentés. Ne jamais utiliser de produits contenant de la menthe poivrée chez le bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Académie de Pédiatrie, EMA',
 NULL),

('bb000010-0000-0000-0000-000000000010',
 'Tea Tree (huile essentielle bébé)',
 'Melaleuca Alternifolia Leaf Oil',
 ARRAY['Tea tree oil', 'Ti tree', 'Melaleuca oil'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'L''huile essentielle de tea tree est déconseillée chez les enfants de moins de 7 ans. Elle contient des terpènes (terpinènes, cymène) qui peuvent être neurotoxiques chez les jeunes enfants dont la barrière hémato-encéphalique n''est pas mature. Des cas d''intoxication avec confusion, ataxie et convulsions ont été rapportés. En application topique chez le bébé, son utilisation est à proscrire. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM pédiatrique, Académie de Pédiatrie',
 NULL),

('bb000011-0000-0000-0000-000000000011',
 'Triclosan (bébé)',
 'Triclosan',
 ARRAY['5-Chloro-2-(2,4-dichlorophenoxy)phenol', 'Irgasan DP 300'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le triclosan est interdit dans les produits de rinçage en Europe depuis 2016 en raison de son activité perturbatrice endocrinienne et du risque de résistances bactériennes. Chez le nourrisson, dont le microbiome cutané est en développement, l''exposition au triclosan peut perturber l''équilibre immunitaire et favoriser des sensibilisations allergiques. Son utilisation est à éviter dans tous les produits de soins bébé. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Règlement EU 1223/2009, SCCS, Que Choisir',
 NULL),

('bb000012-0000-0000-0000-000000000012',
 'DEET (répulsif bébé)',
 'DEET',
 ARRAY['N,N-Diethyl-meta-toluamide', 'N,N-Diethyl-3-methylbenzamide', 'Diethyltoluamide'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Le DEET est un répulsif insecticide puissant dont l''utilisation est formellement contre-indiquée chez les enfants de moins de 2 ans, et doit être utilisé avec extrême précaution chez les enfants de 2 à 12 ans (une application par jour maximum, jamais sur les mains ni le visage). L''absorption cutanée est significative et le DEET peut provoquer des encéphalopathies, convulsions et troubles neurologiques graves chez le jeune enfant. Des alternatives botaniques (Icaridine à 10-20%) sont recommandées. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Académie de Pédiatrie, ANSES',
 NULL),

('bb000013-0000-0000-0000-000000000013',
 'Nanoparticules TiO2/ZnO (produits bébé)',
 'Titanium Dioxide',
 ARRAY['ZnO nano', 'TiO2 nano', 'Zinc Oxide nano', 'nano-TiO2', 'nano-ZnO'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'Les nanoparticules de dioxyde de titane (TiO2) et d''oxyde de zinc (ZnO), utilisées dans les crèmes solaires, présentent un profil de risque préoccupant chez le bébé dont la peau est plus perméable. L''ANSM et le SCCS ont émis des recommandations de précaution pour leur usage chez les nourrissons. L''IARC a classé le TiO2 nanoparticulaire cancérogène possible par inhalation. Pour les bébés, préférez des formulations non-nano ou des crèmes solaires d''écran minéral non-nano. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, SCCS, IARC, Que Choisir',
 NULL),

('bb000014-0000-0000-0000-000000000014',
 'Benzophénone UV (bébé)',
 'Benzophenone-3',
 ARRAY['Oxybenzone', 'Benzophenone', 'BP-3', 'Eusolex 4360'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'danger',
 'La benzophénone-3 (oxybenzone) est un filtre UV chimique interdit dans les crèmes solaires pour enfants dans plusieurs régions. Des études l''ont identifié comme perturbateur endocrinien potentiel avec absorption cutanée significative, détectable dans les urines et le lait maternel. Chez le nourrisson dont la peau est très perméable, l''absorption est encore plus importante. L''Académie Américaine de Pédiatrie recommande d''éviter les filtres chimiques chez les moins de 6 mois et de préférer les filtres minéraux (ZnO, TiO2 non-nano). Consultez votre professionnel de santé pour un avis personnalisé.',
 'Académie de Pédiatrie, Que Choisir, SCCS',
 NULL),

('bb000015-0000-0000-0000-000000000015',
 'Chlorhexidine (bébé)',
 'Chlorhexidine',
 ARRAY['Chlorhexidine gluconate', 'Chlorhexidine digluconate', 'CHX'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'danger',
 'La chlorhexidine est un antiseptique large spectre. Chez le prématuré et le nouveau-né, son application cutanée répétée a été associée à des phénomènes de toxicité systémique en raison de l''absorption percutanée importante. Des cas de dépression respiratoire et de problèmes métaboliques ont été rapportés chez des prématurés. Son utilisation chez le nourrisson de moins de 2 mois doit être strictement médicale et supervisée. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM pédiatrique, OMS néonatologie',
 NULL)

ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- INGRÉDIENTS BÉBÉ — PRÉCAUTION (15)
-- ============================================================
INSERT INTO ingredients (id, name, name_inci, synonyms, category,
  risk_level_t1, risk_level_t2, risk_level_t3, risk_level_breastfeeding, risk_level_baby,
  description_fr, source, source_url)
VALUES

('bc000001-0000-0000-0000-000000000001',
 'SLS / SLES (bébé)',
 'Sodium Lauryl Sulfate',
 ARRAY['SLS', 'SLES', 'Sodium Laureth Sulfate', 'Sodium Lauryl Ether Sulfate'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'caution',
 'Le SLS (Sodium Lauryl Sulfate) et le SLES sont des tensioactifs détergents utilisés dans les shampooings et gels lavants. Chez le bébé, la peau est plus fine et plus sensible, et le SLS peut provoquer des irritations cutanées, altérer la barrière cutanée et favoriser la sensibilisation allergique. Des études ont montré que le SLS peut dénaturer les protéines de la peau. Pour les bébés, préférez des formules "sans SLS/SLES" avec des tensioactifs plus doux (coco glucoside, lauryl glucoside). Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, SCCS, ANSM',
 NULL),

('bc000002-0000-0000-0000-000000000002',
 'Huiles minérales (paraffine bébé)',
 'Paraffinum Liquidum',
 ARRAY['Mineral oil', 'Paraffin', 'Petrolatum', 'Vaseline', 'Huile de paraffine'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Les huiles minérales (paraffine liquide, vaseline) sont largement utilisées dans les crèmes pour bébé et les lingettes. Bien que généralement considérées comme non irritantes, des inquiétudes ont été soulevées concernant les hydrocarbures aromatiques polycycliques (HAP) potentiellement présents en tant qu''impuretés dans les huiles minérales de qualité insuffisante. L''EFSA et Que Choisir recommandent d''utiliser uniquement des huiles minérales de qualité pharmaceutique et de s''orienter vers des alternatives végétales pour les bébés. Consultez votre professionnel de santé pour un avis personnalisé.',
 'EFSA, Que Choisir, ANSM',
 NULL),

('bc000003-0000-0000-0000-000000000003',
 'Lavande non diluée (bébé)',
 'Lavandula Angustifolia Oil',
 ARRAY['Lavender oil', 'Lavandula vera', 'True lavender', 'Huile essentielle de lavande'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'caution',
 'L''huile essentielle de lavande vraie est souvent présentée comme douce et sûre, mais elle doit être utilisée avec précaution chez le bébé. Non diluée, elle peut être irritante pour la peau sensible du nourrisson. La lavande contient du linalool et du linalyle acétate qui ont montré des propriétés oestrogénomimétiques à des concentrations élevées dans certaines études. Pour le bébé, seule la lavande officinale très diluée (1% maximum) peut être envisagée, jamais avant 3 mois. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, ANSM, Académie de Pédiatrie',
 NULL),

('bc000004-0000-0000-0000-000000000004',
 'Colorants artificiels (bébé)',
 'CI 42090',
 ARRAY['Tartrazine', 'CI 19140', 'CI 15985', 'FD&C', 'Colorant azoïque', 'Brilliant Blue FCF'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'caution',
 'Les colorants artificiels (colorants azoïques, CI 42090, 19140...) sont inutiles dans les produits bébé et présentent un risque d''allergie et d''irritation. Certains colorants azoïques sont suspectés d''aggraver l''hyperactivité chez l''enfant (étude McCann, 2007). Pour les produits de soins bébé, aucun colorant artificiel n''est nécessaire et leur présence est un signal de mauvaise formulation. Choisissez des produits sans colorant artificiel. Consultez votre professionnel de santé pour un avis personnalisé.',
 'EFSA, Que Choisir, Règlement EU',
 NULL),

('bc000005-0000-0000-0000-000000000005',
 'BHT / BHA (bébé)',
 'BHT',
 ARRAY['Butylated Hydroxytoluene', 'BHA', 'Butylated Hydroxyanisole', 'Hydroxyanisole'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'caution',
 'Le BHT (butylhydroxytoluène) et le BHA (butylhydroxyanisole) sont des antioxydants synthétiques utilisés dans certains produits cosmétiques pour prolonger leur durée de conservation. Le BHA est classé comme perturbateur endocrinien potentiel de catégorie 1 en Europe. Ces composés peuvent être absorbés par la peau. Chez le bébé, leur utilisation est à éviter au profit d''antioxydants naturels (tocophérol, extrait de romarin). Consultez votre professionnel de santé pour un avis personnalisé.',
 'SCCS, Que Choisir, ANSES',
 NULL),

('bc000006-0000-0000-0000-000000000006',
 'Propylène Glycol (bébé)',
 'Propylene Glycol',
 ARRAY['1,2-Propanediol', 'Propylene glycol', 'PG'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Le propylène glycol est un humectant et solvant très répandu dans les cosmétiques. Chez l''adulte, il est généralement bien toléré. Chez le nourrisson, des cas d''acidose métabolique et d''effets sur le système nerveux central ont été rapportés à des expositions élevées par voie systémique. La peau du bébé étant plus perméable, des concentrations élevées de propylène glycol dans des produits à usage répété méritent d''être évitées, en particulier pour les bébés prématurés. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, Que Choisir',
 NULL),

('bc000007-0000-0000-0000-000000000007',
 'Phtalates (bébé)',
 'Diethyl Phthalate',
 ARRAY['DEP', 'DBP', 'Dibutyl Phthalate', 'DEHP', 'Phthalate'],
 'cosmetic',
 'danger', 'danger', 'danger', 'caution', 'caution',
 'Les phtalates sont des perturbateurs endocriniens. Bien que le DBP et le DEHP soient interdits dans les jouets et les cosmétiques en Europe, le DEP reste autorisé dans les parfums. Chez le nourrisson dont le système endocrinien est en développement, l''exposition aux phtalates par voie cutanée ou par ingestion (mains portées à la bouche) est particulièrement préoccupante. Des études épidémiologiques ont montré des associations entre exposition précoce aux phtalates et perturbations hormonales. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSES, ANSM, Académie de Pédiatrie',
 NULL),

('bc000008-0000-0000-0000-000000000008',
 'PEG / PPG (bébé)',
 'PEG-40 Hydrogenated Castor Oil',
 ARRAY['Polyethylene glycol', 'PEG', 'PPG', 'Polypropylene glycol', 'PEG-4', 'PEG-8'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Les PEG (polyéthylène glycols) et PPG (polypropylène glycols) sont des émulsifiants et humectants largement utilisés dans les cosmétiques. Leur sécurité est débattue sur la peau lésée ou irritée, comme c''est souvent le cas chez les bébés souffrant d''eczéma. Ils peuvent contenir des impuretés (1,4-dioxane, oxyde d''éthylène) en faibles quantités, particulièrement dans les formulations peu contrôlées. Pour les bébés à peau sensible, préférez des émulsifiants naturels (cire d''abeille, lécithine). Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, SCCS, ANSM',
 NULL),

('bc000009-0000-0000-0000-000000000009',
 'EDTA (bébé)',
 'Disodium EDTA',
 ARRAY['Tetrasodium EDTA', 'EDTA', 'Ethylenediaminetetraacetic acid', 'Edetic Acid'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'L''EDTA est un chélateur utilisé pour stabiliser les formules cosmétiques. Sa présence dans les produits pour bébé est inutile et soulève des questions car l''EDTA peut favoriser l''absorption cutanée d''autres substances en augmentant la perméabilité de la membrane cellulaire. Cette propriété de "promoteur de pénétration" est préoccupante chez les nourrissons dont la peau est naturellement plus perméable. Les formulations pour bébé n''ont pas besoin d''EDTA. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, SCCS',
 NULL),

('bc000010-0000-0000-0000-000000000010',
 'Formaldéhyde libérateurs (bébé)',
 'DMDM Hydantoin',
 ARRAY['Formaldehyde', 'Diazolidinyl Urea', 'Imidazolidinyl Urea', 'Quaternium-15', 'Bronopol', '2-Bromo-2-nitropropane-1'],
 'cosmetic',
 'danger', 'danger', 'danger', 'caution', 'caution',
 'Les libérateurs de formaldéhyde (DMDM hydantoïne, imidazolidinyl urée, diazolidinyl urée, Quaternium-15...) libèrent lentement du formaldéhyde, un allergène et cancérogène reconnu. Chez le bébé, la peau est plus sensible et la proportion de peau par rapport au poids corporel est plus élevée. L''exposition répétée à des formaldéhyde libérateurs peut favoriser des sensibilisations cutanées durables. Ces conservateurs sont inutiles dans les produits pour bébé et doivent être évités. Consultez votre professionnel de santé pour un avis personnalisé.',
 'ANSM, SCCS, Que Choisir',
 NULL),

('bc000011-0000-0000-0000-000000000011',
 'Silicones occlusives (bébé)',
 'Dimethicone',
 ARRAY['Cyclomethicone', 'Cyclopentasiloxane', 'D5', 'D4', 'Cyclotetrasiloxane', 'Polysiloxane'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Les silicones cycliques (D4, D5 - cyclotetrassiloxane, cyclopentasiloxane) sont des perturbateurs endocriniens potentiels et font l''objet de restrictions en Europe dans les produits à rincer. Dans les produits laissés sur la peau, les silicones occlusives forment une barrière qui peut piéger les bactéries sur la zone du couche et aggraver les érythèmes fessiers. Pour le bébé, des émollients d''origine végétale (huile de tournesol, beurre de karité) sont préférables. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, Règlement EU 2018/35, SCCS',
 NULL),

('bc000012-0000-0000-0000-000000000012',
 'Fluorures dentifrice (>1000 ppm, bébé)',
 'Sodium Fluoride',
 ARRAY['Fluorure de sodium', 'MFP', 'Monofluorophosphate', 'Stannous Fluoride', 'NaF'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Les dentifrices pour enfants contenant plus de 1000 ppm de fluor sont déconseillés avant 6 ans sans supervision médicale. Chez les bébés et jeunes enfants qui avalent une partie du dentifrice, un excès de fluor peut provoquer une fluorose dentaire (taches blanches permanentes) et, en cas d''ingestion importante, une intoxication aiguë. Les dentifrices pour bébé (dès la première dent) doivent contenir 250-500 ppm de fluor maximum. Consultez votre pédiatre ou dentiste pour un avis personnalisé.',
 'Académie de Pédiatrie, HAS, Ordre des Chirurgiens-Dentistes',
 NULL),

('bc000013-0000-0000-0000-000000000013',
 'Talc (bébé)',
 'Talc',
 ARRAY['Magnesium silicate', 'Talcum powder', 'Poudre de talc'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Le talc (poudre de talc) utilisé dans les soins bébé présente deux risques : l''inhalation accidentelle de fines particules par le nourrisson, pouvant provoquer une pneumonie lipoïde ou des lésions pulmonaires ; et la présence possible d''amiante comme contaminant naturel du talc minéral (IARC catégorie 1 si contaminé). L''Académie Américaine de Pédiatrie déconseille l''utilisation de poudre de talc chez les nourrissons. Des alternatives comme la fécule de maïs sont préférables. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Académie de Pédiatrie, IARC, Que Choisir',
 NULL),

('bc000014-0000-0000-0000-000000000014',
 'Zinc Pyrithione (bébé)',
 'Pyrithione Zinc',
 ARRAY['Zinc pyridinethione', 'ZPT', 'Zinc omadine'],
 'cosmetic',
 'caution', 'caution', 'caution', 'caution', 'caution',
 'Le zinc pyrithione est un agent antifongique et antibactérien utilisé dans les shampooings antipelliculaires et certains savons. Son utilisation chez le nourrisson est déconseillée : il peut provoquer une irritation cutanée et une absorption systémique de zinc potentiellement toxique chez le bébé. Des réactions de sensibilisation ont été rapportées. De plus, depuis 2022, son utilisation dans les produits rincés exposés au milieu aquatique est restreinte en Europe en raison de la toxicité pour les organismes aquatiques. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Règlement EU 2021/1979, SCCS, Que Choisir',
 NULL),

('bc000015-0000-0000-0000-000000000015',
 'Bisabolol de synthèse en excès (bébé)',
 'Bisabolol',
 ARRAY['Alpha-Bisabolol', 'dl-Bisabolol', 'Bisabolol synthétique', 'Levomenol'],
 'cosmetic',
 'safe', 'safe', 'safe', 'safe', 'caution',
 'Le bisabolol naturel (extrait de camomille) est un actif apaisant généralement bien toléré. Cependant, la version synthétique (dl-bisabolol), souvent utilisée en raison de son moindre coût, est un mélange racémique dont le profil de tolérance diffère. À concentrations élevées dans des produits à application répétée sur peau de bébé, certains experts recommandent la prudence. Pour les produits bébé, le bisabolol naturel en concentrations raisonnables (< 0,25%) est préférable à la version synthétique à forte dose. Consultez votre professionnel de santé pour un avis personnalisé.',
 'Que Choisir, SCCS',
 NULL)

ON CONFLICT (id) DO NOTHING;
