import { StyleSheet } from 'react-native';

import { Colors, Radius, Shadows, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
  },
  headerCenter: { flex: 1, alignItems: 'center' },
  backBtn: {
    width: 38, height: 38,
    borderRadius: Radius.full,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.soft,
  },
  shareBtn: {
    width: 38, height: 38,
    borderRadius: Radius.full,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.soft,
  },
  stepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  stepDot: { width: 8, height: 8, borderRadius: Radius.full, backgroundColor: Colors.border },
  stepDotActive: { backgroundColor: Colors.accent, width: 20 },

  // List
  listContent: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.sm, gap: Spacing.md },
  introCard: {
    borderRadius: Radius.xl,
    padding: Spacing.xxl,
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  introEmoji: { fontSize: 48 },
  introTitle: { textAlign: 'center' },
  introSub: { textAlign: 'center' },
  listSectionLabel: { paddingHorizontal: Spacing.xs },
  emptyState: { alignItems: 'center', paddingTop: Spacing.xxl, gap: Spacing.md },
  emptyEmoji: { fontSize: 48 },
  emptySub: { textAlign: 'center', paddingHorizontal: Spacing.xl },

  // Capsule card
  capsuleCard: { borderRadius: Radius.lg, overflow: 'hidden', ...Shadows.soft },
  capsuleGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.lg,
    gap: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  capsuleLockWrap: {
    width: 48, height: 48,
    borderRadius: Radius.full,
    backgroundColor: Colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  capsuleLockWrapOpenable: { backgroundColor: '#FFF5E0' },
  capsuleLockEmoji: { fontSize: 24 },
  capsuleInfo: { flex: 1, gap: 2 },
  capsuleOpenCta: { color: Colors.accentDark, fontFamily: 'PlusJakartaSans_600SemiBold', marginTop: 2 },
  capsuleStats: { alignItems: 'center', gap: Spacing.xs },
  capsuleGlowBadge: {
    backgroundColor: Colors.accentLight,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
  },
  capsuleGlowText: { fontFamily: 'PlusJakartaSans_700Bold', fontSize: 13, color: Colors.accentDark },

  // FAB
  fab: { position: 'absolute', alignSelf: 'center', ...Shadows.elevated },
  fabInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.accentDark,
    paddingHorizontal: Spacing.xxl,
    paddingVertical: Spacing.md + 2,
    borderRadius: Radius.full,
  },
  fabLabel: { fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 15, color: '#FFFFFF' },

  // Sealing overlay
  sealingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(45, 41, 38, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.lg,
  },
  sealingCircle: {
    width: 140, height: 140,
    borderRadius: Radius.full,
    borderWidth: 4,
    borderColor: Colors.accent,
    backgroundColor: 'transparent',
    position: 'absolute',
  },
  sealingLock: { position: 'absolute' },
  sealingLockEmoji: { fontSize: 52 },
  openingLockEmoji: { fontSize: 52 },
  openingLight: {
    position: 'absolute',
    width: 80, height: 80,
    borderRadius: Radius.full,
    backgroundColor: Colors.accent,
  },
  sealingTextWrap: {
    position: 'absolute',
    bottom: 100,
    left: Spacing.xxl,
    right: Spacing.xxl,
    alignItems: 'center',
    gap: Spacing.sm,
  },
  sealingTitle: { color: '#FFFFFF', textAlign: 'center' },
  sealingSub: { color: Colors.accentLight, textAlign: 'center' },
  sealingHint: { color: Colors.textTertiary, textAlign: 'center' },

  // Sparkles
  sparkleContainer: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  sparkle: { position: 'absolute', width: 8, height: 8, borderRadius: Radius.full },

  // Step content
  stepContent: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.huge, gap: Spacing.lg },
  stepTitle: { marginTop: Spacing.sm },
  stepSub: { marginBottom: Spacing.sm },

  // Overview step
  compilingWrap: { alignItems: 'center', paddingVertical: Spacing.xxl },
  overviewGrid: { gap: Spacing.md },
  overviewTile: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.soft,
  },
  overviewEmoji: { fontSize: 28 },
  overviewValue: { color: Colors.accent, minWidth: 40 },
  overviewLabel: { flex: 1 },
  overviewHighlight: {
    backgroundColor: '#FFF9F0',
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.accentLight,
    gap: 4,
  },

  // Personal step
  photoPickerBtn: {
    borderWidth: 2,
    borderColor: Colors.accentLight,
    borderStyle: 'dashed',
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xxl,
    gap: Spacing.sm,
    backgroundColor: '#FFF9F0',
    minHeight: 160,
    overflow: 'hidden',
  },
  photoIcon: { position: 'relative', alignItems: 'center' },
  photoPreview: { width: '100%', height: 200, borderRadius: Radius.md },
  premiumBadgePill: {
    backgroundColor: Colors.accentDark,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    marginLeft: Spacing.sm,
  },
  premiumBadgeText: { fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 10, color: '#FFFFFF' },
  messageSection: { gap: Spacing.sm },
  messageLabelRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  messageInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 15,
    color: Colors.textPrimary,
    backgroundColor: Colors.surface,
    minHeight: 120,
  },
  audioComingSoon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    backgroundColor: Colors.borderLight,
    borderRadius: Radius.lg,
  },

  // Preset (seal step)
  presetList: { gap: Spacing.sm },
  presetCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.lg,
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    borderColor: Colors.border,
    ...Shadows.soft,
  },
  presetCardActive: { borderColor: Colors.accent, backgroundColor: '#FFF9F0' },
  presetEmoji: { fontSize: 28 },
  dateSummary: { alignItems: 'center', paddingVertical: Spacing.lg, gap: Spacing.xs },
  dateSummaryDate: { color: Colors.accentDark },

  // Buttons
  nextBtn: {
    backgroundColor: Colors.textPrimary,
    borderRadius: Radius.full,
    paddingVertical: Spacing.md + 2,
    paddingHorizontal: Spacing.xxl,
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  nextBtnLabel: { fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 15, color: '#FFFFFF' },
  sealBtn: { borderRadius: Radius.full, overflow: 'hidden', ...Shadows.medium },
  sealBtnGradient: { paddingVertical: Spacing.md + 4, paddingHorizontal: Spacing.xxl, alignItems: 'center' },
  sealBtnLabel: { fontFamily: 'PlusJakartaSans_700Bold', fontSize: 17, color: '#FFFFFF' },

  // Content view
  contentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
  },
  contentScroll: { gap: Spacing.xxl, paddingHorizontal: Spacing.lg },
  contentPhotoWrap: { height: 280, marginHorizontal: -Spacing.lg, position: 'relative' },
  contentPhoto: { width: '100%', height: '100%' },
  contentPhotoGradient: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 120 },
  contentHeroBanner: {
    alignItems: 'center',
    padding: Spacing.xxl,
    borderRadius: Radius.xl,
    gap: Spacing.sm,
    marginHorizontal: -Spacing.xs,
  },
  contentHeroEmoji: { fontSize: 48 },
  contentHeroTitle: { color: Colors.accentDark, textAlign: 'center' },
  contentSection: { gap: Spacing.md },
  contentSectionLabel: { paddingHorizontal: Spacing.xs },
  contentStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  contentCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: Spacing.sm,
    ...Shadows.soft,
  },
  scanRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  scanEmoji: { fontSize: 16 },
  firstDangerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingTop: Spacing.sm,
    marginTop: Spacing.xs,
  },
  journalEntryCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: Spacing.sm,
    ...Shadows.soft,
  },
  journalEntryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  journalMood: { fontSize: 24 },
  messageCard: {
    borderRadius: Radius.xl,
    padding: Spacing.xxl,
    borderWidth: 1,
    borderColor: Colors.accentLight,
    gap: Spacing.sm,
  },
  messageQuote: {
    fontSize: 48,
    color: Colors.accentLight,
    fontFamily: 'PlusJakartaSans_700Bold',
    lineHeight: 48,
    marginBottom: -Spacing.md,
  },
  messageText: { fontStyle: 'italic', lineHeight: 28 },
  contentFooter: { alignItems: 'center', paddingTop: Spacing.xl, gap: Spacing.xs },
  footerLogo: { fontFamily: 'PlusJakartaSans_700Bold', fontSize: 22, color: Colors.accent },

  // Stat tile (content view)
  statTile: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.soft,
  },
  statEmoji: { fontSize: 24 },
  statValue: { color: Colors.accent },
  statLabel: { textAlign: 'center' },
});
