uploads = []
generated = []

[[outputs]]
id = "q0JjGmCwnubla7h_0HcBG"
uri = "file://artifacts/helo/helo-code.tar.gz"
type = "unspecified"
title = "helo-code.tar.gz — Code source complet Hēlo"

[[outputs]]
id = "7Ro-M-1jLzHq5b_wasyWZ"
uri = "file://helo-current.tar.gz"
type = "unspecified"
title = "Hēlo — code source propre (2,1 Mo)"

[[outputs]]
id = "hW_tOuP2zqXnPXUZQZFcY"
uri = "file://helo_20260323.tar.gz"
type = "unspecified"
title = "Hēlo — code source complet (23 mars 2026)"

[[outputs]]
id = "vTCDFKV_5fPgaumGqY351"
uri = "file://helo_src_20260323.tar.gz"
type = "unspecified"
title = "Hēlo — code source sans node_modules (23 mars 2026)"
