/**
 * efsa.ts — ~1000 additifs alimentaires et aliments à risque grossesse.
 * Sources: EFSA, ANSES, OMS, CRAT (risques alimentaires).
 * Données pré-calculées — aucun appel réseau.
 */

import { type PreComputedIngredient, type RiskTuple, ing } from '../utils.js';

type R = RiskTuple;
const S: R = ['safe','safe','safe','safe'];
const C: R = ['caution','caution','caution','caution'];
const D: R = ['danger','danger','danger','danger'];
const DC: R = ['danger','caution','caution','caution'];
const DCC: R = ['danger','danger','caution','caution'];
const CD: R = ['caution','caution','danger','caution'];
const CS: R = ['caution','safe','safe','caution'];

function f(ni: string, n: string, r: R, d: string, conf: 'high'|'medium'|'low' = 'high'): PreComputedIngredient {
  return ing(ni, n, 'food', r, d, 'efsa', conf);
}

// ─── Colorants E100–E199 ──────────────────────────────────────────────────────
const COLORANTS: PreComputedIngredient[] = [
  f('E100','Curcumine (E100)',C,'Colorant naturel du curcuma. Propriétés anti-inflammatoires. Considéré sûr à doses alimentaires. Compléments concentrés: précaution.','medium'),
  f('E101','Riboflavine (E101)',S,'Vitamine B2. Essentielle pendant la grossesse. Sûre.'),
  f('E102','Tartrazine (E102)',C,'Colorant azoïque — hypersensibilité chez certaines personnes. Avertissement requis sur les emballages UE. Précaution.'),
  f('E104','Jaune de quinoléine (E104)',C,'Colorant synthétique. Avertissement comportemental UE. Précaution grossesse.','medium'),
  f('E110','Jaune orangé S (E110)',C,'Colorant azoïque. Avertissement comportemental. Précaution grossesse.'),
  f('E120','Carmin / Cochenille (E120)',C,'Colorant naturel animal. Peut provoquer des réactions allergiques. Précaution.'),
  f('E122','Carmoisine (E122)',C,'Colorant azoïque. Avertissement comportemental UE. Précaution grossesse.'),
  f('E123','Amarante (E123)',D,'Colorant azoïque — interdit aux USA. Données préoccupantes reprotoxicité. À éviter.'),
  f('E124','Ponceau 4R (E124)',C,'Colorant azoïque. Avertissement comportemental. Précaution grossesse.'),
  f('E127','Érythrosine (E127)',C,'Colorant iodé synthétique. Peut affecter la thyroïde. Précaution en cas de troubles thyroïdiens.'),
  f('E129','Rouge Allura AC (E129)',C,'Colorant azoïque. Avertissement comportemental UE. Précaution grossesse.'),
  f('E131','Bleu patenté V (E131)',C,'Colorant synthétique. Précaution grossesse.','medium'),
  f('E132','Indigotine (E132)',C,'Colorant indigo synthétique. Précaution.','medium'),
  f('E133','Bleu brillant FCF (E133)',C,'Colorant azoïque. Précaution grossesse.','medium'),
  f('E140','Chlorophylles (E140)',S,'Colorants naturels végétaux. Sûrs.'),
  f('E141','Complexes cuivre-chlorophylle (E141)',C,'Colorants naturels. Teneur en cuivre à surveiller.','medium'),
  f('E150a','Caramel ordinaire (E150a)',S,'Caramel naturel. Sûr.','medium'),
  f('E150d','Caramel au sulfite d\'ammonium (E150d)',C,'Contient 4-méthylimidazole (4-MEI) — cancérogène possible. Précaution.'),
  f('E151','Noir brillant BN (E151)',C,'Colorant azoïque. Précaution grossesse.','medium'),
  f('E153','Charbon végétal (E153)',C,'Absorbant — peut réduire l\'absorption des médicaments. Précaution.','medium'),
  f('E155','Brun HT (E155)',C,'Colorant azoïque. Précaution grossesse.','medium'),
  f('E160a','Bêta-carotène (E160a)',C,'Précurseur de la vitamine A. Sûr à doses alimentaires. Suppléments à forte dose: CONTRE-INDIQUÉS (tératogène).'),
  f('E160b','Annatto / Bixine (E160b)',C,'Colorant naturel de roucou. Allergisant potentiel. Précaution.','medium'),
  f('E160c','Capsanthine (E160c)',S,'Colorant de paprika. Sûr aux doses alimentaires.','medium'),
  f('E161b','Lutéine (E161b)',S,'Caroténoïde. Sûr.','medium'),
  f('E161g','Canthaxanthine (E161g)',D,'Caroténoïde synthétique — accumulation rétinienne documentée. À éviter pendant la grossesse.'),
  f('E162','Rouge de betterave (E162)',S,'Colorant naturel. Sûr.'),
  f('E163','Anthocyanes (E163)',S,'Colorants naturels de fruits. Sûrs.'),
  f('E170','Carbonate de calcium (E170)',S,'Minéral naturel. Sûr.'),
  f('E171','Dioxyde de titane (E171)',D,'INTERDIT dans les aliments en UE depuis 2022. Classé cancérogène potentiel. À éviter absolument.'),
  f('E172','Oxydes de fer (E172)',S,'Pigments minéraux naturels. Sûrs.','medium'),
  f('E173','Aluminium (E173)',C,'Métal — accumulation possible. Limiter l\'exposition pendant la grossesse.','medium'),
  f('E174','Argent (E174)',C,'Métal précieux. Données limités — précaution.','medium'),
  f('E175','Or (E175)',S,'Métal précieux inerte. Sûr en petites quantités.','medium'),
  f('E180','Lithol-rubine BK (E180)',C,'Colorant azoïque. Précaution grossesse.','low'),
];

// ─── Conservateurs E200–E299 ──────────────────────────────────────────────────
const PRESERVATIVES: PreComputedIngredient[] = [
  f('E200','Acide sorbique (E200)',S,'Conservateur naturel. Bien toléré. Sûr pendant la grossesse.'),
  f('E202','Sorbate de potassium (E202)',S,'Sel de l\'acide sorbique. Sûr.'),
  f('E210','Acide benzoïque (E210)',C,'Conservateur. Peut former du benzène avec la vitamine C. Précaution.'),
  f('E211','Benzoate de sodium (E211)',C,'Conservateur — formation benzène potentielle. Précaution grossesse.'),
  f('E212','Benzoate de potassium (E212)',C,'Conservateur. Même précaution que E211.','medium'),
  f('E213','Benzoate de calcium (E213)',C,'Conservateur. Précaution grossesse.','medium'),
  f('E214','Éthyl para-hydroxybenzoate (E214)',C,'Parabène alimentaire. Activité oestrogénique faible. Précaution grossesse.'),
  f('E215','Éthyl para-hydroxybenzoate sodique (E215)',C,'Parabène alimentaire sodique. Précaution grossesse.','medium'),
  f('E216','Propyl para-hydroxybenzoate (E216)',C,'Parabène alimentaire — interdit dans certains aliments UE. Précaution grossesse.'),
  f('E218','Méthyl para-hydroxybenzoate (E218)',C,'Parabène alimentaire. Activité oestrogénique faible. Précaution grossesse.'),
  f('E220','Dioxyde de soufre (E220)',C,'Sulfite — allergisant respiratoire. Vin et fruits séchés. Précaution grossesse.'),
  f('E221','Sulfite de sodium (E221)',C,'Sulfite. Même risque que E220.','medium'),
  f('E222','Bisulfite de sodium (E222)',C,'Sulfite. Précaution allergique.','medium'),
  f('E223','Métabisulfite de sodium (E223)',C,'Sulfite — allergisant. Précaution.'),
  f('E224','Métabisulfite de potassium (E224)',C,'Sulfite. Précaution.','medium'),
  f('E226','Sulfite de calcium (E226)',C,'Sulfite. Précaution.','medium'),
  f('E228','Bisulfite de potassium (E228)',C,'Sulfite. Précaution.','medium'),
  f('E234','Nisine (E234)',S,'Conservateur naturel d\'origine bactérienne. Sûr.','medium'),
  f('E235','Natamycine (E235)',C,'Antifongique — données limités grossesse. Précaution.','medium'),
  f('E242','Diméthyle dicarbonate (E242)',C,'Conservateur des boissons. Données limités grossesse.','medium'),
  f('E249','Nitrite de potassium (E249)',D,'Nitrite — précurseur de nitrosamines (cancérogènes). Viandes transformées. À limiter fortement pendant la grossesse.'),
  f('E250','Nitrite de sodium (E250)',D,'NITRITE — précurseur de nitrosamines. ANSES recommande de limiter fortement pendant la grossesse. Éviter charcuterie cuite.'),
  f('E251','Nitrate de sodium (E251)',C,'Nitrate — converti en nitrite in vivo. Charcuteries. À limiter pendant la grossesse.'),
  f('E252','Nitrate de potassium (E252)',C,'Nitrate alimentaire. À limiter pendant la grossesse.'),
  f('E260','Acide acétique (E260)',S,'Vinaigre — sûr aux doses alimentaires.'),
  f('E270','Acide lactique (E270)',S,'Conservateur naturel. Sûr.'),
  f('E280','Acide propionique (E280)',S,'Conservateur du pain. Sûr aux doses alimentaires.','medium'),
  f('E281','Propionate de sodium (E281)',S,'Conservateur. Sûr.','medium'),
  f('E282','Propionate de calcium (E282)',S,'Conservateur du pain. Sûr.','medium'),
  f('E284','Acide borique (E284)',D,'Acide borique — toxique à fortes doses. À éviter pendant la grossesse.','medium'),
  f('E285','Tétraborate de sodium (borax) (E285)',D,'Perturbateur endocrinien — INTERDIT dans de nombreux pays. À éviter.'),
];

// ─── Antioxydants E300–E399 ───────────────────────────────────────────────────
const ANTIOXIDANTS: PreComputedIngredient[] = [
  f('E300','Acide ascorbique / Vitamine C (E300)',S,'Antioxydant naturel. Essentiel pendant la grossesse. Sûr.'),
  f('E301','Ascorbate de sodium (E301)',S,'Vitamine C sodique. Sûr.'),
  f('E302','Ascorbate de calcium (E302)',S,'Vitamine C calcique. Sûr.'),
  f('E304','Palmitate d\'ascorbyle (E304)',S,'Ester de vitamine C. Sûr aux doses alimentaires.','medium'),
  f('E306','Tocophérols naturels (Vit E) (E306)',S,'Vitamine E naturelle. Essentielle. Sûre.'),
  f('E307','Alpha-tocophérol synthétique (E307)',S,'Vitamine E synthétique. Sûre aux doses alimentaires.','medium'),
  f('E310','Gallate de propyle (E310)',C,'Antioxydant — données limités grossesse. Précaution.','medium'),
  f('E315','Acide érythorbique (E315)',S,'Antioxydant dérivé de l\'acide ascorbique. Sûr.','medium'),
  f('E320','BHA (Butylhydroxyanisole) (E320)',C,'Antioxydant synthétique — cancérogène possible (groupe 2B). À éviter pendant la grossesse.'),
  f('E321','BHT (Butylhydroxytoluène) (E321)',C,'Antioxydant synthétique — perturbateur endocrinien potentiel. À éviter pendant la grossesse.'),
  f('E322','Lécithines (E322)',S,'Émulsifiant naturel. Sûr.'),
  f('E325','Lactate de sodium (E325)',S,'Antioxydant synergiste. Sûr.','medium'),
  f('E330','Acide citrique (E330)',S,'Antioxydant naturel. Sûr.'),
  f('E331','Citrate de sodium (E331)',S,'Antioxydant. Sûr.'),
  f('E332','Citrate de potassium (E332)',S,'Antioxydant. Sûr.','medium'),
  f('E333','Citrate de calcium (E333)',S,'Antioxydant. Sûr.','medium'),
  f('E334','Acide tartrique (E334)',S,'Antioxydant naturel. Sûr.','medium'),
  f('E338','Acide phosphorique (E338)',C,'Acidifiant — consommation excessive de phosphates déconseillée. Précaution.'),
  f('E339','Phosphate disodique (E339)',C,'Sel phosphate. Consommation excessive à éviter.','medium'),
  f('E340','Phosphate monopotassique (E340)',C,'Sel phosphate. Précaution.','medium'),
  f('E341','Phosphate de calcium (E341)',C,'Sel phosphate. Précaution consommation excessive.','medium'),
  f('E343','Phosphate de magnésium (E343)',C,'Sel phosphate. Précaution.','medium'),
  f('E350','Malate de sodium (E350)',S,'Acide malique sodique. Sûr.','medium'),
  f('E353','Acide métatartrique (E353)',S,'Acide organique. Sûr.','medium'),
  f('E355','Acide adipique (E355)',S,'Acide organique. Sûr aux doses alimentaires.','medium'),
  f('E363','Acide succinique (E363)',S,'Acide naturel. Sûr.','medium'),
  f('E380','Citrate de triammonium (E380)',C,'Émulsifiant. Données limités grossesse.','low'),
  f('E385','EDTA calcique disodique (E385)',C,'Chélateur — peut réduire l\'absorption des minéraux essentiels. Précaution.','medium'),
];

// ─── Épaississants / Gélifiants E400–E499 ────────────────────────────────────
const THICKENERS: PreComputedIngredient[] = [
  f('E400','Acide alginique (E400)',S,'Alginate naturel. Sûr.','medium'),
  f('E401','Alginate de sodium (E401)',S,'Alginate naturel. Sûr.'),
  f('E402','Alginate de potassium (E402)',S,'Alginate naturel. Sûr.','medium'),
  f('E404','Alginate de calcium (E404)',S,'Alginate. Sûr.','medium'),
  f('E405','Alginate de propylène glycol (E405)',C,'Alginate modifié. Données grossesse limités. Précaution.','medium'),
  f('E406','Agar-agar (E406)',S,'Gélifiant naturel d\'algues. Sûr.'),
  f('E407','Carraghénanes (E407)',C,'Épaississant marin — inflammation intestinale documentée chez l\'animal. Données limités grossesse. À éviter en excès.'),
  f('E407a','Carraghénanes transformés (E407a)',C,'Carraghénanes dégradés — préoccupations santé. Précaution grossesse.','medium'),
  f('E410','Farine de graines de caroube (E410)',S,'Gélifiant naturel. Sûr.'),
  f('E412','Gomme de guar (E412)',S,'Épaississant naturel. Sûr.'),
  f('E413','Gomme adragante (E413)',C,'Épaississant naturel — allergisant potentiel. Précaution.','medium'),
  f('E414','Gomme arabique (E414)',S,'Épaississant naturel. Sûr.'),
  f('E415','Gomme xanthane (E415)',S,'Épaississant fermenté. Sûr.'),
  f('E416','Gomme karaya (E416)',C,'Épaississant naturel — allergisant potentiel.','medium'),
  f('E417','Gomme tara (E417)',S,'Épaississant végétal. Sûr.','medium'),
  f('E418','Gomme gellane (E418)',S,'Épaississant fermenté. Sûr.','medium'),
  f('E420','Sorbitol (E420)',S,'Polyol. Sûr. Peut provoquer ballonnements en excès.','medium'),
  f('E421','Mannitol (E421)',S,'Polyol. Sûr.','medium'),
  f('E422','Glycérol (E422)',S,'Humectant naturel. Sûr.'),
  f('E432','Polysorbate 20 (E432)',C,'Émulsifiant PEGylé — contaminants potentiels (1,4-dioxane). Précaution.','medium'),
  f('E433','Polysorbate 80 (E433)',C,'Émulsifiant PEGylé. Précaution.','medium'),
  f('E440','Pectines (E440)',S,'Épaississant naturel de fruits. Sûr.'),
  f('E450','Diphosphates (E450)',C,'Phosphates — consommation excessive déconseillée pendant la grossesse.','medium'),
  f('E452','Polyphosphates (E452)',C,'Phosphates — précaution consommation excessive.','medium'),
  f('E460','Cellulose (E460)',S,'Fibre insoluble. Sûre.'),
  f('E461','Méthylcellulose (E461)',S,'Cellulose modifiée. Sûre.','medium'),
  f('E464','Hydroxypropylméthylcellulose (E464)',S,'Dérivé cellulosique. Sûr.','medium'),
  f('E466','Carboxyméthylcellulose (E466)',S,'Dérivé cellulosique. Sûr.','medium'),
  f('E471','Mono- et diglycérides d\'acides gras (E471)',S,'Émulsifiants naturels. Sûrs.'),
  f('E472e','Esters diacétyltartriques de mono/diglycérides (E472e)',S,'Émulsifiant du pain. Sûr.','medium'),
  f('E476','Polyglycérol polyricinolate (E476)',C,'Émulsifiant du chocolat — données grossesse limitées. Précaution.','medium'),
  f('E481','Stéaroyl-2-lactylate de sodium (E481)',S,'Émulsifiant du pain. Sûr.','medium'),
  f('E491','Monostéarate de sorbitane (E491)',S,'Émulsifiant. Sûr.','medium'),
];

// ─── Exhausteurs de goût E620–E699 ────────────────────────────────────────────
const FLAVOR_ENHANCERS: PreComputedIngredient[] = [
  f('E621','Glutamate monosodique (E621)',C,'Exhausteur de goût (MSG) — données contradictoires sur effets fœtaux. À consommer avec modération pendant la grossesse.'),
  f('E622','Glutamate monopotassique (E622)',C,'Exhausteur. Même précaution que E621.','medium'),
  f('E623','Glutamate de calcium (E623)',C,'Exhausteur. Précaution.','medium'),
  f('E624','Glutamate monoammoniacal (E624)',C,'Exhausteur. Précaution.','medium'),
  f('E625','Glutamate de magnésium (E625)',C,'Exhausteur. Précaution.','medium'),
  f('E626','Acide guanylique (E626)',C,'Exhausteur. Précaution.','medium'),
  f('E627','Guanylate disodique (E627)',C,'Exhausteur. Précaution grossesse.','medium'),
  f('E630','Acide inosinique (E630)',C,'Exhausteur — peut aggraver la goutte. Précaution.','medium'),
  f('E631','Inosinate disodique (E631)',C,'Exhausteur. Précaution.','medium'),
  f('E635','Ribonucléotide disodique (E635)',C,'Exhausteur combiné. Précaution grossesse.','medium'),
  f('E640','Glycine et sel de sodium (E640)',S,'Acide aminé. Sûr.','medium'),
  f('E650','Acétate de zinc (E650)',C,'Zinc alimentaire. Zinc essentiel mais excès déconseillé.','medium'),
];

// ─── Édulcorants E950–E999 ────────────────────────────────────────────────────
const SWEETENERS: PreComputedIngredient[] = [
  f('E950','Acésulfame K (E950)',C,'Édulcorant synthétique — données limités grossesse. Précaution par principe de précaution.'),
  f('E951','Aspartame (E951)',C,'Édulcorant synthétique — contient phénylalanine. CONTRE-INDIQUÉ en cas de phénylcétonurie. Précaution générale grossesse.'),
  f('E952','Cyclamate (E952)',D,'INTERDIT dans de nombreux pays — données de cancérogénicité préoccupantes. À éviter pendant la grossesse.'),
  f('E953','Isomalt (E953)',S,'Polyol. Sûr aux doses modérées.','medium'),
  f('E954','Saccharine (E954)',DC,'Traverse le placenta — déconseillée pendant le 1er trimestre. Données préoccupantes en animal.'),
  f('E955','Sucralose (E955)',C,'Édulcorant chloré — données grossesse limitées. Précaution par principe.','medium'),
  f('E957','Thaumatine (E957)',S,'Protéine édulcorante naturelle. Sûre.','medium'),
  f('E959','Néohespéridine DC (E959)',C,'Édulcorant. Données limités grossesse.','medium'),
  f('E960','Glycosides de stéviol / Stevia (E960)',C,'Édulcorant naturel — données grossesse limitées. Usage modéré considéré acceptable.','medium'),
  f('E961','Néotame (E961)',C,'Édulcorant synthétique. Données grossesse insuffisantes. Précaution.','medium'),
  f('E962','Sel d\'aspartame-acésulfame (E962)',C,'Contient aspartame. Même précaution que E951.','medium'),
  f('E968','Érythritol (E968)',S,'Polyol naturel. Bien toléré. Sûr.','medium'),
  f('E969','Advantame (E969)',C,'Édulcorant synthétique. Données grossesse très limités.','low'),
];

// ─── Agents de traitement E900–E949 ───────────────────────────────────────────
const PROCESSING_AIDS: PreComputedIngredient[] = [
  f('E900','Diméthylpolysiloxane (E900)',S,'Anti-mousse. Sûr aux doses alimentaires.','medium'),
  f('E901','Cire d\'abeille (E901)',S,'Naturelle. Sûre.'),
  f('E903','Cire de carnauba (E903)',S,'Cire végétale. Sûre.'),
  f('E904','Gomme shellac (E904)',S,'Résine naturelle. Sûre.','medium'),
  f('E905','Cire microcristalline (E905)',C,'Dérivé pétrolier. Données limités grossesse. Précaution.','medium'),
  f('E920','L-cystéine (E920)',C,'Acide aminé améliorant de farine. Données limités grossesse.','medium'),
  f('E927b','Urée (E927b)',S,'Régulateur de fermentation. Sûr.','medium'),
  f('E938','Argon (E938)',S,'Gaz inerte. Sûr.','medium'),
  f('E941','Azote (E941)',S,'Gaz inerte. Sûr.','medium'),
  f('E942','Protoxyde d\'azote (E942)',C,'Gaz — anesthésique. Pas en usage alimentaire intensif pendant la grossesse.','medium'),
  f('E943a','Butane (E943a)',C,'Gaz propulseur. Précaution inhalation.','medium'),
  f('E948','Oxygène (E948)',S,'Gaz naturel. Sûr.','medium'),
];

// ─── Aliments à risque infectieux (listériose, toxoplasmose, salmonellose) ────
const INFECTION_RISKS: PreComputedIngredient[] = [
  f('FROMAGE AU LAIT CRU','Fromage au lait cru',D,'LISTÉRIOSE — les fromages au lait cru (camembert, brie, roquefort, fromages de chèvre frais) peuvent contenir Listeria monocytogenes. CONTRE-INDIQUÉS pendant la grossesse.'),
  f('FROMAGE PATE MOLLE CROUTE FLEURIE','Fromage à pâte molle à croûte fleurie',D,'Risque élevé de listériose (camembert, brie). CONTRE-INDIQUÉS pendant la grossesse — même pasteurisés si la croûte est conservée.'),
  f('CHARCUTERIE CUITE','Charcuterie cuite (jambon, pâté)',D,'Risque de listériose — à éviter sauf chauffée à cœur. Préférer le jambon cuit en tranches sous vide récemment ouvert.'),
  f('RILLETTES','Rillettes, pâtés, foie gras',D,'Risque de listériose — à éviter. Foie gras: aussi riche en vitamine A (tératogène à excès).'),
  f('VIANDE CRUE','Viande crue ou peu cuite (tartare, carpaccio)',D,'TOXOPLASMOSE et listériose. CONTRE-INDIQUÉS pendant la grossesse si non immunisée.'),
  f('POISSON CRU','Poisson cru (sushi, sashimi, tartare)',D,'LISTÉRIOSE — Listeria peut coloniser le saumon fumé et les poissons crus. À éviter pendant la grossesse.'),
  f('SAUMON FUME','Saumon fumé (smoked salmon)',D,'Listériose — risque documenté. À éviter pendant la grossesse. Sûr si cuit à cœur.'),
  f('OEUF CRU','Œuf cru ou insuffisamment cuit',D,'SALMONELLOSE — tiramisu, mayonnaise maison, œuf à la coque. À éviter pendant la grossesse.'),
  f('GRAINES GERMEES','Graines germées (pousses)',D,'Bactéries (E.coli, Salmonella, Listeria). CONTRE-INDIQUÉES pendant la grossesse.'),
  f('JUS FRUITS NON PASTEURISE','Jus de fruits non pasteurisé',D,'Risque bactérien et E.coli. À éviter pendant la grossesse.'),
  f('LAIT CRU','Lait cru (non pasteurisé)',D,'Listériose, salmonellose, campylobactériose. CONTRE-INDIQUÉ pendant la grossesse.'),
  f('FROMAGE FONDUE RACLETTE','Fondue, raclette (fromages fondus chauds)',S,'Si chauffés à cœur (>70°C): risques bactériens éliminés. Sûrs si bien cuits.'),
  f('SOJA CRU','Soja fermenté (tofu, miso, tempeh)',C,'Phytoestrogènes — propriétés oestrogéniques potentielles. À consommer avec modération.','medium'),
  f('FENUGREC GRAINES','Graines de fenugrec',C,'Propriétés utérotoniques documentées — déconseillées au 1er trimestre en grande quantité.','medium'),
  f('PAPAYE CRU','Papaye crue (non mûre)',DC,'Contient papaïne — effet utérotonique documenté. À éviter en 1er trimestre. Papaye mûre cuite: sûre.','medium'),
  f('ANANAS JUS','Jus d\'ananas frais',C,'Contient bromélaïne — effets utérins potentiels. À consommer avec modération.','medium'),
  f('EPINARDS CRUS','Épinards et légumes-feuilles crus',C,'Toxoplasmose si mal lavés. Laver soigneusement ou cuire pendant la grossesse.','medium'),
  f('SUSHI','Sushi / maki',D,'Poisson cru + riz vinaigré: risques cumulés listériose et parasites. À éviter.'),
];

// ─── Poissons à risque mercure ────────────────────────────────────────────────
const MERCURY_FISH: PreComputedIngredient[] = [
  f('THON ROUGE','Thon rouge (Thunnus thynnus)',D,'MERCURE ÉLEVÉ — bioaccumulation. ANSES: à éviter pendant la grossesse. Remplacer par des petits poissons gras.'),
  f('ESPADON','Espadon (Xiphias gladius)',D,'TRÈS FORTE TENEUR EN MERCURE. CONTRE-INDIQUÉ pendant la grossesse.'),
  f('REQUIN','Requin (squales)',D,'MERCURE TRÈS ÉLEVÉ. CONTRE-INDIQUÉ pendant la grossesse et l\'allaitement.'),
  f('MARLIN','Marlin',D,'MERCURE TRÈS ÉLEVÉ. À éviter absolument pendant la grossesse.'),
  f('BROCHET','Brochet (Esox lucius)',D,'MERCURE ÉLEVÉ — eau douce. ANSES: à éviter pendant la grossesse.'),
  f('LAMPROIE','Lamproie',D,'MERCURE ÉLEVÉ + dioxines. À éviter pendant la grossesse.'),
  f('THON GERMON','Thon albacore (thon en boîte léger)',C,'Mercure modéré. ANSES: limiter à 1 portion/semaine pendant la grossesse.'),
  f('THON BLANC','Thon blanc (germon) en conserve',C,'Mercure modéré — limiter à 1 portion/semaine.','medium'),
  f('SARDINE','Sardine',S,'Petit poisson gras — faible mercure, riche en oméga-3. Recommandé 2x/semaine pendant la grossesse.'),
  f('MAQUEREAU','Maquereau',S,'Petit poisson gras — riche en oméga-3, mercure faible. Recommandé pendant la grossesse.'),
  f('HARENG','Hareng',S,'Petit poisson — faible mercure, riche en oméga-3. Recommandé.'),
  f('ANCHOIS','Anchois (Engraulis encrasicolus)',S,'Petit poisson — mercure très faible. Riche en oméga-3. Recommandé.'),
  f('SAUMON ATLANTIQUE','Saumon de l\'Atlantique (élevage)',C,'Mercure faible mais peut contenir polluants organiques. Limiter à 2 portions/semaine.','medium'),
  f('DAURADE','Daurade royale',S,'Mercure faible. Protéines de qualité. Sûr.','medium'),
  f('CABILLAUD','Cabillaud (morue)',S,'Poisson maigre — mercure faible. Sûr et nutritif.'),
  f('SOLE','Sole',S,'Poisson maigre. Faible mercure. Sûr.','medium'),
];

// ─── Caféine et stimulants ────────────────────────────────────────────────────
const CAFFEINE_SOURCES: PreComputedIngredient[] = [
  f('CAFEINE','Caféine',C,'Maximum 200 mg/j pendant la grossesse (EFSA/ANSES). Doses élevées liées au RCIU et fausse couche. 1 café ≈ 80-100 mg.'),
  f('CAFE','Café (Coffea arabica/robusta)',C,'Source principale de caféine. Limiter à 2 tasses/jour (café faible) ou 1 espresso. Décaféiné: sûr.'),
  f('THE NOIR','Thé noir (Camellia sinensis)',C,'Caféine (50 mg/tasse) + tanins réduisant l\'absorption du fer. Limiter à 2-3 tasses/jour.'),
  f('THE VERT','Thé vert (Camellia sinensis)',C,'Caféine (30-50 mg/tasse) + EGCG — données limités grossesse. Limiter à 2 tasses/jour.'),
  f('COLA','Boissons cola (Coca-Cola, Pepsi)',C,'Caféine (35-40 mg/250ml) + sucre. Limiter à 500ml/jour.','medium'),
  f('CHOCOLAT NOIR','Chocolat noir (Theobroma cacao)',C,'Caféine et théobromine. Limiter la consommation excessive. 30-40g/jour: sûr.','medium'),
  f('BOISSONS ENERGISANTES','Boissons énergisantes (Red Bull, Monster)',D,'CONTRE-INDIQUÉES pendant la grossesse — teneur en caféine très élevée + autres stimulants (taurine, guarana).'),
  f('GUARANA','Guarana (Paullinia cupana)',D,'Source concentrée de caféine. CONTRE-INDIQUÉ pendant la grossesse — dose imprévisible.'),
  f('MATE','Maté (Ilex paraguariensis)',C,'Caféine élevée + composés potentiellement génotoxiques. Déconseillé pendant la grossesse.'),
  f('YERBA MATE','Yerba maté',C,'Riche en caféine et composés préoccupants. Déconseillé grossesse.','medium'),
];

// ─── Alcool ───────────────────────────────────────────────────────────────────
const ALCOHOL: PreComputedIngredient[] = [
  f('ALCOOL ETHYLIQUE ALIMENTAIRE','Alcool éthylique (boissons alcoolisées)',D,'AUCUNE DOSE SÛRE pendant la grossesse. Syndrome d\'alcoolisation fœtale (SAF) — abstinence totale recommandée par OMS, CRAT, HAS.'),
  f('VIN','Vin (rouge, blanc, rosé)',D,'Alcool — contre-indiqué pendant toute la grossesse, quel que soit le volume.'),
  f('BIERE','Bière',D,'Alcool — contra-indiquée. La bière sans alcool (<0,5% vol): considérée sûre.'),
  f('BIERE SANS ALCOOL','Bière sans alcool (<0,5% vol)',C,'Traces d\'alcool possibles. Généralement considérée sûre en consommation modérée. Précaution.','medium'),
  f('SPIRITS','Spiritueux (whisky, vodka, gin, rhum)',D,'Alcool à très haute teneur. Absolument contre-indiqué.'),
  f('CIDRE','Cidre alcoolisé',D,'Alcool — contre-indiqué.','medium'),
  f('KOMBUCHA ALCOOLISE','Kombucha fermenté (>0,5% vol)',C,'Peut contenir de l\'alcool (variable). Précaution. Certains kombucha sont alcoolisés.','medium'),
  f('TIRAMISU','Tiramisu (contient mascarpone + alcool + œuf cru)',D,'Triple risque: alcool + œuf cru (salmonelle) + fromage frais (listériose). À éviter.'),
];

// ─── Vitamines et minéraux alimentaires ───────────────────────────────────────
const VITAMINS_MINERALS: PreComputedIngredient[] = [
  f('ACIDE FOLIQUE','Acide folique (Vitamine B9)',S,'ESSENTIEL pendant la grossesse — 400 µg/j minimum avant conception et 1er trimestre. Prévient les anomalies du tube neural. Sûr.'),
  f('VITAMINE D3','Vitamine D3 (Cholécalciférol)',C,'Essentielle pendant la grossesse. Supplémentation recommandée (1000-2000 UI/j). Fortes doses (>4000 UI/j): toxicité. Précaution si supplément.',),
  f('FER ALIMENTAIRE','Fer (supplémentation)',C,'Besoin accru pendant la grossesse. Supplémentation sur prescription médicale. Surdosage: effets négatifs.'),
  f('IODE','Iode',C,'Oligo-élément essentiel. Carence: hypothyroïdie fœtale. Excès (>500 µg/j): blocage thyroïde fœtale. Équilibre important.'),
  f('OMEGA 3 DHA','Oméga-3 DHA (acide docosahexaénoïque)',S,'Essentiel pour le développement cérébral fœtal. 200 mg/j recommandés. Sûr.'),
  f('VITAMINE A ALIMENT','Vitamine A (rétinol alimentaire)',D,'CONTRE-INDIQUÉ > 10000 UI/j — tératogène. Foie d\'animaux très riche — à éviter. Bêta-carotène végétal: sûr.'),
  f('VITAMINE B12','Vitamine B12 (Cobalamine)',S,'Essentielle. Carences chez les végétaliens. Supplémentation nécessaire si régime végétalien. Sûre.'),
  f('VITAMINE B6','Vitamine B6 (Pyridoxine)',C,'Aide contre les nausées de grossesse (B6+doxylamine). Doses élevées (>100 mg/j): neuropathie. Modération.','medium'),
  f('VITAMINE K1','Vitamine K1 (Phylloquinone)',S,'Coagulation. Sûre aux doses alimentaires. Injection prophylactique au nouveau-né recommandée.'),
  f('VITAMINE C ALIMENT','Vitamine C (acide ascorbique alimentaire)',S,'Antioxydant essentiel. Sûre aux doses alimentaires. Mégadoses (>2g/j): diarrhées.','medium'),
  f('CALCIUM ALIMENTAIRE','Calcium',S,'Essentiel pour la minéralisation fœtale. Besoins augmentés. Produits laitiers ou compléments. Sûr.'),
  f('MAGNESIUM ALIMENT','Magnésium',S,'Prévient les crampes nocturnes. Sûr aux doses alimentaires. Fortes doses: laxatif.','medium'),
  f('ZINC ALIMENTAIRE','Zinc',C,'Oligo-élément essentiel. Carence déconseillée. Suppléments à doses élevées: précaution (inhibe absorption du cuivre).','medium'),
  f('SELENIUM ALIMENTAIRE','Sélénium',C,'Oligo-élément essentiel. Toxique à fortes doses (> 400 µg/j). Équilibre.','medium'),
  f('CUIVRE ALIMENTAIRE','Cuivre',C,'Oligo-élément essentiel. Toxique en excès. Modération.','medium'),
  f('VITAMINE E ALIMENT','Vitamine E alimentaire',S,'Antioxydant. Sûre aux doses alimentaires. Fortes doses (>1000 mg/j): précaution.','medium'),
  f('CHOLINE','Choline',S,'Essentielle pour le développement cérébral. Les œufs en sont une source majeure. Sûre.','medium'),
  f('INOSITOL','Inositol (vitamine B8)',C,'Données préliminaires sur prévention du diabète gestationnel. Données insuffisantes — précaution.','medium'),
  f('ACIDE ALPHA LIPOIQUE','Acide alpha-lipoïque (ALA)',C,'Antioxydant — données grossesse insuffisantes. Précaution.','medium'),
];

// ─── Herbes et plantes alimentaires à risque ─────────────────────────────────
const HERBS_FOOD: PreComputedIngredient[] = [
  f('PERSIL HUILE','Persil en grande quantité / huile essentielle',DC,'Contient apiol — propriétés abortives à fortes doses. Usage culinaire normal: sûr. Compléments/HE: contre-indiqués.'),
  f('SAUGE ALIMENTAIRE','Sauge (condiment)',DC,'Petites quantités en cuisine: sûres. Infusions fortes / HE: déconseillées au 1er trimestre (emménagogue).','medium'),
  f('CANNELLE FORTE','Cannelle en grandes quantités',C,'Contient cinnamaldéhyde — propriétés utérotoniques à fortes doses. Condiment usuel: sûr.','medium'),
  f('REGLISSE ALIMENTAIRE','Réglisse (bonbons, infusions)',C,'Glycyrrhizine — perturbateur endocrinien, augmente tension artérielle. ANSES: < 100 mg/j pendant la grossesse. Éviter les bonbons réglissés.'),
  f('GINGEMBRE ALIMENTAIRE','Gingembre (Zingiber officinale)',C,'Anti-nausée efficace en 1er trimestre. Doses médicinales (>2g/j): précaution. Usage culinaire: sûr.','medium'),
  f('THYM ALIMENTAIRE','Thym (condiment)',S,'Condiment: sûr aux doses culinaires usuelles. HE de thym: déconseillée.'),
  f('ROMARIN ALIMENTAIRE','Romarin (condiment)',C,'Condiment: sûr en petites quantités. Infusions fortes / compléments: précaution.','medium'),
  f('MENTHE POIVREE INFUSION','Infusion de menthe poivrée',C,'Quantités modérées: généralement tolérées. Fortes doses ou HE: précaution.','medium'),
  f('CAMOMILLE INFUSION','Infusion de camomille',C,'Boisson apaisante. Données grossesse limitées — précaution au 1er trimestre.','medium'),
  f('HIBISCUS INFUSION','Infusion d\'hibiscus (karkadé)',C,'Contient phytoestrogènes potentiels. Déconseillée en 1er trimestre.','medium'),
  f('FRAMBOISIER FEUILLE','Infusion de feuille de framboisier (Rubus idaeus)',DC,'Déconseillée en 1er et 2e trimestres. Parfois utilisée en fin de grossesse (à terme uniquement et sur avis médical).'),
  f('GATTILIER','Gattilier (Vitex agnus-castus)',D,'Modifie les hormones — CONTRE-INDIQUÉ pendant la grossesse.'),
  f('VALERIANE','Valériane (Valeriana officinalis)',C,'Sédatif — données grossesse insuffisantes. Précaution.','medium'),
  f('DONG QUAI','Dong quaï (Angelica sinensis)',D,'Plante de MTC — propriétés utérotoniques. CONTRE-INDIQUÉ pendant la grossesse.'),
  f('BLACK COHOSH','Actée à grappes noires (Cimicifuga racemosa)',D,'Activité oestrogénique et utérotonique documentée. CONTRE-INDIQUÉE.'),
  f('EPHEDRA','Éphédra (Ma Huang)',D,'Stimulant cardiaque et vasoconstricteur — CONTRE-INDIQUÉ.'),
  f('CURCUMA FORTE','Curcuma (compléments concentrés)',C,'Condiment: sûr. Compléments à haute dose: précaution — données grossesse limitées.','medium'),
  f('SPIRULINE','Spiruline (complément)',C,'Algue riche en protéines. Risque de contamination aux cyanotoxines. Précaution qualité.','medium'),
  f('CHLORELLE','Chlorelle (complément)',C,'Algue. Risque de contamination. Précaution grossesse.','medium'),
];

// ─── Acides gras trans et lipides préoccupants ────────────────────────────────
const FATS: PreComputedIngredient[] = [
  f('TRANS GRAS','Acides gras trans (graisses hydrogénées)',C,'Acides gras industriels — OMS recommande de les éliminer. Perturbent le métabolisme lipidique. À éviter.'),
  f('HUILE PALME','Huile de palme',C,'Riche en acides gras saturés. Données nutritionnelles préoccupantes en excès. Précaution.','medium'),
  f('MARGARINES HYDROGENUEES','Margarines hydrogénées (contenant trans)',C,'Contiennent acides gras trans. À éviter pendant la grossesse.','medium'),
  f('HUILE DE COCO ALIMENTAIRE','Huile de coco (alimentaire)',C,'Très riche en graisses saturées. Usage modéré recommandé.','medium'),
];

// ─── Polluants alimentaires ───────────────────────────────────────────────────
const POLLUTANTS: PreComputedIngredient[] = [
  f('PESTICIDES RESIDUS','Résidus de pesticides (fruits/légumes)',C,'Précaution: laver soigneusement ou choisir bio pour les fruits les plus exposés (pommes, fraises, poivrons).','medium'),
  f('AFLATOXINES','Aflatoxines (moisissures)',D,'Mycotoxines cancérogènes — présentes dans noix, maïs, arachides mal conservés. CONTRE-INDIQUÉES.'),
  f('DIOXINES PCB','Dioxines et PCB (poissons gras)',C,'Polluants organiques persistants — poissons gras de la Baltique. Limiter à 1 portion/semaine.','medium'),
  f('ACRYLAMIDE ALIMENT','Acrylamide (aliments frits/cuits haute température)',C,'Cancérogène probable — chips, frites très cuites, café. Précaution — limiter les aliments très grillés.','medium'),
  f('HAP ALIMENT','Hydrocarbures aromatiques polycycliques (HAP)',C,'Cancérogènes — grillades au charbon, poissons fumés. Précaution — cuisson modérée.','medium'),
  f('BPA ALIMENTAIRE','Bisphénol A (boîtes de conserve)',C,'Perturbateur endocrinien — boîtes de conserve et plastiques. Préférer le frais ou le verre.'),
];

// ─── FROMAGES — STATUT PASTEURISATION ─────────────────────────────────────
const CHEESES: PreComputedIngredient[] = [
  f('CAMEMBERT AU LAIT CRU','Camembert au lait cru',D,'Listériose et toxoplasmose — lait non pasteurisé. INTERDIT en grossesse.'),
  f('BRIE AU LAIT CRU','Brie au lait cru',D,'Lait cru — risque listériose. INTERDIT en grossesse.'),
  f('ROQUEFORT','Roquefort',D,'Fromage à pâte persillée — lait cru. INTERDIT en grossesse.'),
  f('BLEU D\'AUVERGNE','Bleu d\'Auvergne',D,'Pâte persillée lait cru — INTERDIT en grossesse.'),
  f('GORGONZOLA','Gorgonzola (importé)',D,'Bleu — peut être au lait cru. Vérifier pasteurisation. Précaution.','medium'),
  f('STILTON','Stilton',D,'Pâte persillée — risque listériose. À éviter.','medium'),
  f('SAINT-NECTAIRE AU LAIT CRU','Saint-Nectaire lait cru',D,'Lait non pasteurisé — INTERDIT.'),
  f('MUNSTER AU LAIT CRU','Munster lait cru',D,'Fromage à croûte lavée, lait cru — INTERDIT.'),
  f('LIVAROT','Livarot',D,'Croûte lavée, lait cru — risque listériose. INTERDIT.'),
  f('PONT-L\'EVEQUE','Pont-l\'Évêque lait cru',D,'Croûte lavée — lait cru. INTERDIT.'),
  f('EPOISSES','Époisses',D,'Croûte lavée — lait cru ou pasteurisé. Listériose fréquente. INTERDIT.'),
  f('MAROILLES','Maroilles',D,'Croûte lavée — souvent lait cru. INTERDIT.'),
  f('VACHERIN MONT-D\'OR','Vacherin Mont-d\'Or',D,'Lait cru, croûte lavée — listériose. INTERDIT.'),
  f('REBLOCHON AU LAIT CRU','Reblochon lait cru',D,'Lait non pasteurisé — INTERDIT en grossesse.'),
  f('COULOMMIERS AU LAIT CRU','Coulommiers lait cru',D,'Pâte molle lait cru — INTERDIT.'),
  f('FROMAGE DE CHEVRE AU LAIT CRU','Fromage de chèvre lait cru',D,'Crottin, Sainte-Maure, etc. lait cru — INTERDIT.'),
  f('FROMAGE DE BREBIS AU LAIT CRU','Fromage de brebis lait cru',D,'Ossau-Iraty lait cru, pélardon — INTERDIT.'),
  f('CAMEMBERT PASTEURISE','Camembert pasteurisé (Label)',S,'Pasteurisé industriel — sûr si sans croûte.'),
  f('BRIE PASTEURISE','Brie pasteurisé',S,'Pâte molle pasteurisée — sûr. Éviter la croûte.','medium'),
  f('COMTÉ','Comté (AOP)',S,'Pâte pressée cuite — lait cru mais cuisson élimine pathogènes. Sûr.'),
  f('GRUYERE','Gruyère',S,'Pâte dure cuite — lait cru mais sûr par cuisson. Sûr.'),
  f('EMMENTAL','Emmental',S,'Pâte dure — très bien cuit. Sûr.'),
  f('BEAUFORT','Beaufort',S,'Pâte pressée cuite — sûr.'),
  f('ABONDANCE','Abondance',S,'Pâte dure — sûr.'),
  f('PARMESAN (PARMIGIANO REGGIANO)','Parmesan (affiné 12 mois)',S,'Long affinage tue les pathogènes. Sûr.'),
  f('PECORINO ROMANO','Pecorino Romano (affiné)',S,'Long affinage — sûr.'),
  f('GRANA PADANO','Grana Padano',S,'Pâte dure affinée — sûr.'),
  f('CHEDDAR (PASTEURISE)','Cheddar pasteurisé',S,'Fromage industriel — sûr.'),
  f('GOUDA','Gouda',S,'Pâte demi-dure — pasteurisé généralement. Sûr.'),
  f('EDAM','Édam',S,'Fromage pasteurisé — sûr.'),
  f('MOZZARELLA INDUSTRIELLE','Mozzarella industrielle pasteurisée',S,'Pasteurisée — sûr.'),
  f('MOZZARELLA DI BUFALA','Mozzarella di bufala',D,'Souvent lait non pasteurisé — INTERDIT. Vérifier l\'étiquette.','medium'),
  f('RICOTTA PASTEURISEE','Ricotta pasteurisée industrielle',S,'Pasteurisée — sûr.'),
  f('FETA (AOP)','Feta (AOP)',C,'Lait brebis/chèvre — pasteurisation variable. Vérifier étiquette.','medium'),
  f('HALLOUMI','Halloumi',S,'Fromage chypriote cuit — sûr en version pasteurisée.','medium'),
  f('MANCHEGO AFFINE','Manchego affiné (+60j)',S,'Long affinage — sûr.'),
  f('EMMENTAL RAPE','Emmental râpé (cuisine)',S,'Pasteurisé — sûr.'),
  f('FROMAGE FONDU','Fromage fondu (vache qui rit etc.)',S,'Transformation thermique — très sûr.'),
  f('FROMAGE A TARTINER','Fromage à tartiner (Philadelphia etc.)',S,'Pasteurisé — sûr.'),
  f('COTTAGE CHEESE PASTEURISE','Cottage cheese pasteurisé',S,'Fromage frais pasteurisé — sûr.'),
  f('SKYR','Skyr',S,'Laitage fermenté pasteurisé islandais — sûr.'),
  f('QUESO FRESCO','Queso fresco',D,'Fromage mexicain souvent lait cru non pasteurisé — INTERDIT.'),
  f('PANEER','Paneer',C,'Fromage indien — vérifier pasteurisation. Précaution.','medium'),
  f('RACLETTE PASTEURISEE','Raclette (pasteurisée, fondue)',S,'Chauffée — pathogènes détruits. Sûr.'),
  f('FONDUE SAVOYARDE','Fondue savoyarde (chauffée)',S,'Cuisson à ébullition — sûr.'),
  f('FOURME D\'AMBERT','Fourme d\'Ambert',D,'Bleu à pâte persillée — listériose. À éviter.','medium'),
  f('BLEU DE BRESSE','Bleu de Bresse',D,'Fromage bleu — lait cru. À éviter.','medium'),
  f('LANGRES','Langres',D,'Croûte lavée lait cru — à éviter.','medium'),
  f('CANTAL VIEUX','Cantal vieux (affiné)',S,'Long affinage — sûr.'),
  f('SAINT-FELICIEN','Saint-Félicien',D,'Pâte molle lait cru — risque. À éviter.','medium'),
  f('BRILLAT-SAVARIN','Brillat-Savarin',C,'Pâte molle triple crème — vérifier pasteurisation.','medium'),
];

// ─── ESPÈCES DE POISSONS & FRUITS DE MER ──────────────────────────────────
const FISH_SPECIES: PreComputedIngredient[] = [
  f('THON ROUGE','Thon rouge (bluefin tuna)',D,'Très forte teneur en mercure. Limiter strictement en grossesse — max 150g/semaine recommandé par ANSES.'),
  f('REQUIN','Requin (aileron, steak)',D,'Mercure très élevé — grand prédateur. INTERDIRE en grossesse.'),
  f('ESPADON','Espadon',D,'Mercure très élevé — INTERDIT en grossesse (ANSES).'),
  f('MARLIN','Marlin',D,'Mercure très élevé — INTERDIT en grossesse.'),
  f('MAKAIRE','Makaire',D,'Grand prédateur — mercure élevé. À éviter.'),
  f('KAISERIN THON','Thon obèse (bigeye tuna)',D,'Mercure élevé — à éviter en grossesse.'),
  f('VOILIER','Poisson voilier (sailfish)',D,'Mercure — INTERDIT.'),
  f('SIKI','Siki (small shark)',D,'Commercialisé comme "saumon" dans certains pays — mercure. Attention.','medium'),
  f('LAMPROIE','Lamproie',D,'Mercure et PCB élevés — INTERDIT en grossesse.'),
  f('BROCHET','Brochet',D,'Mercure élevé — eau douce. À éviter en grossesse.'),
  f('SILURE','Silure',D,'Grand prédateur eau douce — mercure et PCB. À éviter.'),
  f('FLÉTAN DE L\'ATLANTIQUE','Flétan de l\'Atlantique',C,'Mercure modéré — 1 portion/sem max. Précaution.','medium'),
  f('LOTTE DE MER','Lotte/baudroie',C,'Mercure modéré — limiter 1 portion/sem.','medium'),
  f('THON EN BOITE','Thon en boîte (albacore/listao)',C,'Listao: 2 portions/sem max. Albacore: 1 portion/sem. Limiter.','medium'),
  f('MAQUEREAU','Maquereau (atlantique)',S,'Riche oméga-3, mercure faible. 2 portions/sem recommandées.'),
  f('HARENG','Hareng',S,'Riche oméga-3 — mercure très faible. Recommandé.'),
  f('SARDINE','Sardine',S,'Oméga-3 et calcium. Mercure faible. Recommandé 2x/sem.'),
  f('ANCHOIS','Anchois (frais/conserve)',S,'Riche oméga-3 — mercure faible. Sûr. Attention sel en conserve.'),
  f('SAUMON DE L\'ATLANTIQUE','Saumon de l\'Atlantique (élevage)',S,'Oméga-3 élevés — mercure faible. Cuire à cœur. Recommandé.'),
  f('SAUMON SAUVAGE','Saumon sauvage (Alaska)',S,'Oméga-3 excellents — mercure faible. Cuire à cœur.'),
  f('SAUMON FUME','Saumon fumé',D,'Listériose — non cuit. INTERDIT en grossesse cru.'),
  f('TRUITE ARC-EN-CIEL','Truite arc-en-ciel (élevage)',S,'Oméga-3 — mercure très faible. Bien cuire.'),
  f('TRUITE FARIO','Truite sauvage',S,'Mercure variable selon milieu. Sûr si bien cuite.','medium'),
  f('CABILLAUD','Cabillaud (morue fraîche)',S,'Poisson blanc maigre — mercure faible. Sûr.'),
  f('COLIN (LIEU NOIR)','Colin/lieu noir',S,'Poisson blanc maigre. Mercure très faible. Sûr.'),
  f('MERLU','Merlu',S,'Poisson blanc — mercure faible. Sûr.'),
  f('JULIENNE','Julienne/lingue',S,'Poisson blanc — sûr.'),
  f('TACAUD','Tacaud',S,'Petit poisson blanc — mercure faible. Sûr.'),
  f('GRONDIN','Grondin',S,'Poisson rouge-rose — mercure faible. Sûr.'),
  f('SAINT-PIERRE','Saint-Pierre',S,'Poisson plat délicat — mercure faible. Sûr.'),
  f('SOLE','Sole',S,'Poisson plat — mercure faible. Sûr.'),
  f('TURBOT','Turbot',C,'Poisson plat — mercure modéré. 1 portion/sem.','medium'),
  f('BARBUE','Barbue',C,'Poisson plat — mercure modéré. Précaution.','medium'),
  f('LIMANDE','Limande',S,'Poisson plat — mercure faible. Sûr.'),
  f('CARDINE','Cardine',S,'Poisson plat — sûr.'),
  f('ROUGET BARBET','Rouget barbet',S,'Poisson rouge — mercure faible. Sûr. Foie riche en vitamines.'),
  f('PAGEOT','Pageot',S,'Poisson blanc méditerranéen — sûr.'),
  f('DAURADE ROYALE','Daurade royale',S,'Poisson de mer — mercure faible. Sûr si bien cuit.'),
  f('DORADE GRISE','Dorade grise',S,'Poisson méditerranéen — sûr.'),
  f('MULET','Mulet/muge',C,'Peut être chargé en PCB selon milieu. Précaution eaux polluées.','medium'),
  f('BAR (LOUP)','Bar/loup de mer',C,'Mercure modéré — 1 portion/sem.','medium'),
  f('ESTURGEON','Esturgeon (caviar interdit)',D,'Poisson d\'eau douce — PCB et mercure. Caviar : listériose si cru. À éviter.'),
  f('PERCHE','Perche',C,'Eau douce — mercure variable. Précaution.','medium'),
  f('SANDRE','Sandre',C,'Eau douce — mercure modéré. Précaution.','medium'),
  f('CARPE','Carpe',C,'Poisson eau douce — peut accumuler PCB. Précaution.','medium'),
  f('GARDON','Gardon',C,'Petit poisson eau douce — précaution eaux polluées.','medium'),
  f('ANGUILLE','Anguille',D,'PCB et mercure très élevés — INTERDIT grossesse.'),
  f('SPRAT','Sprat (éperlan baltique)',S,'Petit poisson — mercure faible. Sûr.'),
  f('HARENG FUME','Hareng fumé/kippers',C,'Non cuit — listériose. Précaution.','medium'),
  f('MORUE SALEE','Morue salée/stockfish (cuite)',S,'Cod séché salé — bien réhydraté et cuit. Sûr.'),
  f('TILAPIA','Tilapia (élevage)',S,'Poisson d\'élevage — mercure très faible. Sûr.'),
  f('PANGASIUS','Pangasius/basa',S,'Poisson d\'élevage — mercure faible. Sûr si cuit.'),
  f('PERCHE DU NIL','Perche du Nil',C,'Grand prédateur — mercure modéré.','medium'),
  f('LOTTE D\'EAU DOUCE','Lotte d\'eau douce (burbot)',C,'Eau douce — précaution.','medium'),
  f('RAIE','Raie',C,'Cartilagineux — mercure modéré. 1 portion/sem.','medium'),
  f('ROUSSETTE','Roussette (petit requin)',D,'Requin — mercure. À éviter.'),
  f('RASCASSE','Rascasse',S,'Poisson rocheux — mercure faible. Sûr.'),
  f('CHAPON DE MER','Chapon',S,'Poisson rocher — sûr.'),
  f('VIVE','Poisson vive',S,'Poisson — sûr si bien cuit.'),
  f('GIRELLE','Girelle',S,'Petit poisson méditerranéen — sûr.'),
  f('POISSON CRUE (SASHIMI/SUSHI)','Sashimi, sushi, poisson cru',D,'Listériose et anisakis — INTERDIT en grossesse. Cuire à cœur.'),
  f('POISSON FUME (GENERIQUE)','Poisson fumé (générique)',D,'Non cuit — listériose. À éviter. OK si chauffé >70°C.'),
  f('POISSON MARINE CRU','Mariné cru (ceviche, gravlax)',D,'Non cuit — listériose et anisakis. INTERDIT.'),
  // Coquillages et crustacés
  f('HUITRES CRUES','Huîtres crues',D,'Vibrio, norovirus, hépatite A — INTERDIT en grossesse.'),
  f('HUITRES CUITES','Huîtres cuites (>70°C)',S,'Cuisson élimine pathogènes. Sûr.'),
  f('CREVETTES CUITES','Crevettes cuites',S,'Bien cuites — sûr. Oméga-3 et protéines.'),
  f('CREVETTES CRUES','Crevettes crues',D,'Listériose et bactéries — INTERDIT cru.'),
  f('CREVETTES GRISES (GRISES)','Crevettes grises (bouquets)',S,'Cuites fraîches — sûr.'),
  f('HOMARD CUIT','Homard cuit',S,'Cuit à l\'eau bouillante — sûr.'),
  f('LANGOUSTINE CUITE','Langoustine cuite',S,'Bien cuite — sûr.'),
  f('LANGOUSTE CUITE','Langouste cuite',S,'Bien cuite — sûr.'),
  f('CRABE CUIT','Crabe cuit',S,'Cuit — sûr. Mercure faible.'),
  f('MOULES CUITES','Moules cuites',S,'Bien cuites — sûr (valves ouvertes).'),
  f('MOULES CRUES','Moules crues',D,'Bactéries et norovirus — INTERDIT.'),
  f('PALOURDES CUITES','Palourdes cuites',S,'Cuites — sûr.'),
  f('COQUES CUITES','Coques cuites',S,'Cuites — sûr.'),
  f('PRAIRES CUITES','Praires cuites',S,'Cuites — sûr.'),
  f('SAINT-JACQUES CRU','Saint-Jacques cru (carpaccio)',D,'Cru — listériose. INTERDIT.'),
  f('SAINT-JACQUES CUIT','Saint-Jacques cuit',S,'Poêlé — sûr.'),
  f('POULPE CUIT','Poulpe cuit',S,'Cuit — sûr. Mercure faible.'),
  f('CALMAR CUIT','Calmar cuit',S,'Cuit — sûr.'),
  f('SEICHE CUITE','Seiche cuite',S,'Cuite — sûr.'),
  f('SURIMI','Surimi (bâtonnets de mer)',S,'Poisson blanc pasteurisé — sûr. Attention sel.'),
  f('CRUSTACES EN CONSERVE','Crustacés en conserve (thon/saumon)',S,'Pasteurisés — sûrs.'),
];

// ─── VIANDES & CHARCUTERIES ───────────────────────────────────────────────
const MEAT_TYPES: PreComputedIngredient[] = [
  f('STEAK SAIGNANT','Steak saignant/bleu',D,'Toxoplasmose — viande insuffisamment cuite. INTERDIT.'),
  f('STEAK TARTARE','Steak tartare',D,'Cru — toxoplasmose et bactéries. INTERDIT.'),
  f('CARPACCIO DE BOEUF','Carpaccio de bœuf',D,'Cru — toxoplasmose. INTERDIT.'),
  f('VIANDE BIEN CUITE','Viande bien cuite (à cœur, >71°C)',S,'Cuisson suffisante — sûr.'),
  f('POULET BIEN CUIT','Poulet/volaille bien cuit',S,'Cuit à >74°C — sûr.'),
  f('POULET CRU','Poulet cru (tartare de volaille)',D,'Salmonelle — INTERDIT cru.'),
  f('DINDE','Dinde bien cuite',S,'Volaille — sûr si bien cuite.'),
  f('CANARD BIEN CUIT','Canard bien cuit',S,'Bien cuit — sûr.'),
  f('CANARD CUIT ROSÉ','Magret de canard rosé',D,'Insuffisamment cuit — toxoplasmose. INTERDIT.'),
  f('FOIE GRAS','Foie gras (cuit)',C,'Foie — riche en vitamine A (rétinoïdes). Limiter à 1x/sem.','medium'),
  f('FOIE DE VEAU','Foie de veau (en grande quantité)',C,'Riche en vitamine A — limiter.','medium'),
  f('AGNEAU BIEN CUIT','Agneau/mouton bien cuit',S,'Cuit à cœur — sûr.'),
  f('VEAU BIEN CUIT','Veau bien cuit',S,'Viande blanche bien cuite — sûr.'),
  f('PORC BIEN CUIT','Porc bien cuit',S,'Cuisson nécessaire (>71°C) — trichines. Sûr si cuit.'),
  f('BOUDIN NOIR','Boudin noir (cuit)',S,'Cuit — sûr. Riche en fer.'),
  f('ANDOUILLETTE','Andouillette',C,'Charcuterie cuite mais non stérilisée — précaution listériose.','medium'),
  f('JAMBON BLANC CUIT','Jambon blanc pasteurisé',S,'Pasteurisé — sûr.'),
  f('JAMBON CRU','Jambon cru (serrano, parma, cru)',D,'Non cuit — toxoplasmose. INTERDIT.'),
  f('SAUCISSON SEC','Saucisson sec/salami',D,'Séché non cuit — toxoplasmose. INTERDIT.'),
  f('CHORIZO CRU','Chorizo cru',D,'Charcuterie non cuite — toxoplasmose. INTERDIT.'),
  f('CHORIZO CUIT','Chorizo cuit (fondu)',C,'Si chauffé à >70°C — sûr. Sinon INTERDIT.','medium'),
  f('SALAMI','Salami',D,'Charcuterie séchée — INTERDIT cru.'),
  f('RILLETTES','Rillettes (stérilisées)',S,'Stérilisées — sûr.'),
  f('PÂTÉ EN BOITE','Pâté stérilisé',S,'Stérilisé — sûr.'),
  f('PÂTÉ EN CROUTE','Pâté en croûte non stérilisé',D,'Lésion listériose — INTERDIT.','medium'),
  f('MOUSSE DE CANARD ARTISANALE','Mousse artisanale (non stérilisée)',D,'Listériose — INTERDIT.'),
  f('MERGUEZ','Merguez (bien cuite)',S,'Saucisse cuite — sûr si bien grillée.'),
  f('CHIPOLATA BIEN CUITE','Chipolata bien cuite',S,'Saucisse cuite — sûr.'),
  f('GIBIER','Gibier sauvage (sanglier, chevreuil)',D,'Toxoplasmose et trichinose — précaution. Cuire à cœur.','medium'),
  f('LAPIN BIEN CUIT','Lapin bien cuit',S,'Sûr si cuit à cœur.'),
  f('ABATS (AUTRES)','Abats (reins, cœur, rate)',C,'Toxines et métaux lourds possibles. Précaution.','medium'),
  f('BEEF JERKY','Beef jerky / viande séchée',D,'Séchée — peut ne pas atteindre T° suffisante. Précaution listériose.','medium'),
];

// ─── HERBES, ÉPICES & ASSAISONNEMENTS ────────────────────────────────────
const HERBS_SPICES_2: PreComputedIngredient[] = [
  f('SAFRAN GRANDE QUANTITE','Safran (grande quantité)',D,'Utérotonique à hautes doses — culinaire OK. Supplements CONTRE-INDIQUÉS.','medium'),
  f('SAFRAN CULINAIRE','Safran (usage culinaire)',S,'Dose alimentaire — sûr.'),
  f('CANNELLE CULINAIRE','Cannelle (usage culinaire)',S,'Épice — sûr aux doses culinaires.'),
  f('CANNELLE SUPPLEMENTS','Cannelle (suppléments/huile)',C,'Huile: cinnamaldéhyde — précaution grossesse à hautes doses.','medium'),
  f('CURCUMA CULINAIRE','Curcuma (épice)',S,'Antioxydant alimentaire — sûr aux doses culinaires.'),
  f('CURCUMA SUPPLEMENTS','Curcuma (gélules/extrait)',C,'Hautes doses anticoagulantes — précaution grossesse.','medium'),
  f('GINGEMBRE CULINAIRE','Gingembre (racine fraîche)',S,'Antiémétique naturel — sûr et recommandé nausées de grossesse.'),
  f('GINGEMBRE SUPPLEMENTS','Gingembre (suppléments >1g/j)',C,'Hautes doses — précaution T3 (anticoagulant).','medium'),
  f('PERSIL CULINAIRE','Persil (herbe alimentaire)',S,'Sûr aux doses culinaires.'),
  f('PERSIL HUILE/GRAINES','Persil (huile, grandes quantités)',D,'Apiole — abortif à hautes doses. INTERDIT suppléments.'),
  f('SAUGE ALIMENTAIRE','Sauge (assaisonnement culinaire)',S,'Sûr aux doses alimentaires.'),
  f('SAUGE SUPPLEMENT','Sauge (tisane forte, huile)',D,'Thurjone — neurotoxique et utérotonique. INTERDIT.'),
  f('THYM CULINAIRE','Thym (herbe)',S,'Antimicrobien naturel — sûr en cuisine.'),
  f('ORIGAN CULINAIRE','Origan (herbe)',S,'Épice méditerranéenne — sûr.'),
  f('ROMARIN CULINAIRE','Romarin (herbe)',S,'Antioxydant — sûr aux doses alimentaires.'),
  f('ROMARIN HUILE ESSENTIELLE','Romarin (huile essentielle)',D,'Cétones — neurotoxique à hautes doses. CONTRE-INDIQUÉ.'),
  f('BASILIC CULINAIRE','Basilic (herbe fraîche)',S,'Sûr en cuisine.'),
  f('CORIANDRE HERBE','Coriandre (fraîche, graine)',S,'Herbe aromatique — sûr.'),
  f('MENTHE FRAICHE','Menthe fraîche (herbe)',S,'Tisane douce — sûr en usage modéré.'),
  f('POIVRE NOIR','Poivre noir',S,'Épice universelle — sûr.'),
  f('POIVRE BLANC','Poivre blanc',S,'Sûr.'),
  f('POIVRE ROUGE','Poivre de Cayenne (piment)',S,'Capsaïcine — sûr aux doses alimentaires.'),
  f('PAPRIKA','Paprika (piment doux)',S,'Épice rouge — sûr.'),
  f('PIMENT FORT','Piment fort (jalapeño, habanero)',S,'Épicé — sûr. Peut aggraver reflux gastrique.','medium'),
  f('MUSCADE CULINAIRE','Noix de muscade (petite quantité)',S,'Sûr aux doses culinaires.'),
  f('MUSCADE EXCESS','Noix de muscade (grande quantité)',D,'Myristicine — neurotoxique, hallucinogène. INTERDIT en excès.'),
  f('CLOU DE GIROFLE CULINAIRE','Clou de girofle (cuisine)',S,'Sûr aux petites doses culinaires.'),
  f('FENOUIL GRAINES CUISINE','Fenouil (graines, cuisine)',S,'Sûr aux doses alimentaires.'),
  f('ANIS ETOILE CUISINE','Anis étoilé (badiane, cuisine)',S,'Sûr aux doses alimentaires.'),
  f('CARDAMOME','Cardamome',S,'Épice — sûr.'),
  f('CUMIN','Cumin',S,'Épice — sûr.'),
  f('CORIANDRE GRAINE','Coriandre (graine)',S,'Épice — sûr.'),
  f('FENUGREC CULINAIRE','Fenugrec (cuisine)',C,'Phytooestrogènes et utérotonique — limiter en grossesse. Précaution.','medium'),
  f('CURRY','Curry (mélange d\'épices)',S,'Mélange — sûr en cuisine.'),
  f('GARAM MASALA','Garam masala',S,'Mélange épices — sûr.'),
  f('RAS EL HANOUT','Ras el hanout',S,'Mélange d\'épices — sûr.'),
  f('EPICES CHINOISES 5','Cinq épices chinoises',S,'Mélange — sûr.'),
  f('LAURIER FEUILLES','Laurier (feuilles, cuisine)',S,'Arôme culinaire — sûr.'),
  f('ESTRAGON FRAIS','Estragon (herbe)',S,'Sûr aux doses alimentaires.'),
  f('CERFEUIL','Cerfeuil',S,'Herbe fine — sûr.'),
  f('CIBOULETTE','Ciboulette',S,'Herbe — sûr.'),
  f('ANETHE','Aneth (dill)',S,'Herbe — sûr aux doses culinaires.'),
  f('HYSOPE','Hysope',C,'Ketones — précaution grossesse.','medium'),
  f('CAPUCINE FLEURS','Capucines (fleurs comestibles)',S,'Sûr.','medium'),
  f('VIOLETTE CULINAIRE','Violettes comestibles',S,'Sûr.','medium'),
  f('SEL DE MER','Sel marin',S,'Condiment — sûr (limiter l\'excès hypertension).','medium'),
  f('SEL IODE','Sel iodé',S,'Iode essentiel — nécessaire grossesse. Recommandé.'),
  f('FLEUR DE SEL','Fleur de sel',S,'Sel naturel — sûr.'),
  f('POIVRE DE SICHUAN','Poivre de Sichuan',S,'Épice — sûr.','medium'),
];

// ─── THÉS & INFUSIONS ─────────────────────────────────────────────────────
const TEAS_INFUSIONS: PreComputedIngredient[] = [
  f('THE VERT (CAFÉINE)','Thé vert',C,'Caféine (~20-40mg/tasse) + EGCG — limiter à 1-2 tasses/j. Acide folique réduit.','medium'),
  f('THE NOIR (CAFÉINE)','Thé noir',C,'Caféine (~40-70mg/tasse) — limiter à 2 tasses/j. Précaution folates.','medium'),
  f('THE BLANC','Thé blanc',C,'Caféine faible — limiter. Antioxydants.','medium'),
  f('THE OOLONG','Thé oolong',C,'Caféine modérée — limiter.','medium'),
  f('THE MATCHA','Thé matcha (poudre)',C,'Caféine concentrée (~70mg/g) — limiter strictement.','medium'),
  f('MATE','Maté',C,'Caféine élevée et acide tannique — limiter à 1 tasse/j.','medium'),
  f('ROOIBOS','Rooibos (thé rouge)',S,'Sans caféine — antioxydants. Sûr et recommandé grossesse.'),
  f('TISANE CAMOMILLE','Tisane de camomille',S,'Calmante — sûr en usage modéré.'),
  f('TISANE VERVEINE','Tisane de verveine citronnelle',S,'Calmante — sûr.'),
  f('TISANE TILLEUL','Tisane de tilleul',S,'Calmant naturel. Sûr.'),
  f('TISANE HIBISCUS','Tisane d\'hibiscus (bissap)',C,'Peut réduire tension — précaution grossesse à hautes doses.','medium'),
  f('TISANE FENOUIL','Tisane de fenouil',D,'Anéthol — phytooestrogène. DÉCONSEILLÉ en grossesse.'),
  f('TISANE ANIS','Tisane d\'anis',D,'Anéthol — DÉCONSEILLÉ.'),
  f('TISANE REGLISSE','Tisane de réglisse',D,'Glycyrrhizine — élève cortisol, TA. INTERDIT en grossesse.'),
  f('TISANE SAUGE','Tisane de sauge',D,'Thurjone — utérotonique. INTERDIT.'),
  f('TISANE FRAMBOISE (FEUILLES)','Tisane de feuilles de framboisier',D,'Utérotonique — INTERDIT T1-T2. Controversée T3.'),
  f('TISANE MENTHE POIVREE','Tisane de menthe poivrée',C,'Menthol — peut relâcher sphincter oesophagien. Modérer. Précaution T1.','medium'),
  f('TISANE GINGEMBRE','Tisane de gingembre (racine fraîche)',S,'Antiémétique — recommandé nausées grossesse.'),
  f('TISANE CITRON MELISSE','Tisane de mélisse',S,'Calmante — sûr.'),
  f('TISANE LAVANDE','Tisane de lavande',S,'Calmante — sûr en usage modéré.'),
  f('TISANE ORANGER FLEUR','Eau de fleur d\'oranger, tilleul',S,'Calmante — sûr.'),
  f('TISANE ROMARIN','Tisane de romarin (légère)',C,'Précaution — doses alimentaires OK. Forte concentration déconseillée.','medium'),
  f('TISANE VALÉRIANE','Tisane de valériane',C,'Sédatif — données insuffisantes grossesse. Précaution.','medium'),
  f('TISANE SUREAU','Tisane de fleur de sureau',S,'Antivirale douce — sûr.'),
  f('TISANE CALENDULA','Tisane de calendula',C,'Utérotonique possible — précaution grossesse.','medium'),
  f('TISANE ECHINACEA','Tisane d\'échinacée',C,'Immunostimulant — données limitées grossesse. Précaution.','medium'),
  f('TISANE GINKGO','Tisane de ginkgo biloba',C,'Anticoagulant — précaution T3.','medium'),
  f('TISANE PASSIFLORE','Tisane de passiflore',C,'Sédatif — données limitées. Précaution grossesse.','medium'),
  f('KEFIR (BOISSON)','Kéfir de lait fermenté',S,'Probiotiques naturels — sûr si pasteurisé.'),
  f('KOMBUCHA','Kombucha',C,'Légèrement alcoolisé, caféiné — précaution grossesse.','medium'),
  f('KEFIR D\'EAU','Kéfir d\'eau',C,'Légèrement alcoolisé — précaution.','medium'),
  f('THE DETOX','Thés/tisanes "detox" (génériques)',D,'Contiennent souvent des plantes abortives/hépatotoxiques. DÉCONSEILLÉ.'),
  f('YERBA MATE','Yerba maté (infusion)',C,'Caféine + tanins — limiter.','medium'),
];

// ─── NOIX, GRAINES & OLÉAGINEUX ──────────────────────────────────────────
const NUTS_SEEDS: PreComputedIngredient[] = [
  f('ARACHIDE (CACAHUETE)','Arachide/cacahuète',S,'Légumineuse oléagineuse — sûr. Allergie possible chez l\'enfant mais pas de restriction prouvée.','medium'),
  f('NOIX DE CAJOU','Noix de cajou',S,'Riche magnésium et protéines — sûr.'),
  f('AMANDE','Amande',S,'Riche calcium et vitamine E — recommandé.'),
  f('NOIX','Noix (de Grenoble)',S,'Riche oméga-3 ALA — recommandé grossesse.'),
  f('NOIX DE PECAN','Noix de pécan',S,'Sûr — riche en graisses bonnes.'),
  f('NOIX DU BRESIL','Noix du Brésil',C,'Très riche en sélénium — limiter à 2-3 noix/j (excès toxique).','medium'),
  f('NOISETTE','Noisette',S,'Riche vitamine E et acide folique — sûr.'),
  f('MACADAMIA','Noix de macadamia',S,'Riche acides gras monoinsaturés — sûr.'),
  f('PISTACHE','Pistache',S,'Protéines, fer, folates — sûr.'),
  f('PIGNON DE PIN','Pignon de pin',S,'Riche en acides gras — sûr.'),
  f('NOIX DE COCO FRAICHE','Noix de coco (chair fraîche)',S,'Hydratante — sûr.'),
  f('GRAINES DE SÉSAME','Graines de sésame',S,'Riche calcium et fer — recommandé.'),
  f('TAHINI (PÂTE DE SÉSAME)','Tahini',S,'Riche calcium — sûr.'),
  f('GRAINES DE LIN','Graines de lin',C,'Lignanes phytooestrogènes — précaution en grandes quantités en grossesse.','medium'),
  f('HUILE DE LIN','Huile de lin',S,'Riche ALA oméga-3 — sûr.'),
  f('GRAINES DE CHIA','Graines de chia',S,'Oméga-3 ALA, calcium, fer — recommandé.'),
  f('GRAINES DE CHANVRE','Graines de chanvre (hemp seeds)',S,'Oméga-3/6 équilibrés, protéines complètes. Sûr (sans THC).'),
  f('GRAINES DE TOURNESOL','Graines de tournesol',S,'Vitamine E et magnésium. Sûr.'),
  f('GRAINES DE COURGE','Graines de courge',S,'Zinc et magnésium. Sûr.'),
  f('GRAINES DE PAVOT','Graines de pavot (alimentaire)',S,'Sûr aux doses alimentaires.','medium'),
  f('GRAINES DE MOUTARDE','Graines de moutarde',S,'Épice — sûr.'),
  f('BEURRE DE CACAHUETE','Beurre de cacahuète',S,'Protéines et acide folique. Sûr.'),
  f('BEURRE D\'AMANDE','Beurre d\'amande',S,'Calcium, protéines. Sûr.'),
  f('BEURRE DE NOIX DE CAJOU','Beurre de noix de cajou',S,'Sûr.'),
  f('GRAINES DE TOURNESOL GERMEES','Pousses de tournesol',S,'Germées — sûr si fraîches et bien lavées.'),
  f('NOIX DE GINKGO','Noix de ginkgo (alimentaire)',C,'Ginkgotoxine — précaution grossesse (neurotoxique à hautes doses).','medium'),
  f('CHÂTAIGNE','Châtaigne',S,'Glucides complexes, sans gluten. Sûr.'),
  f('LUPIN (GRAINE)','Lupin (farine, graines)',C,'Allergie croisée cacahuète possible. Précaution.','medium'),
];

// ─── PRODUITS LAITIERS ────────────────────────────────────────────────────
const DAIRY_PRODUCTS: PreComputedIngredient[] = [
  f('LAIT CRU','Lait cru non pasteurisé',D,'Listériose, salmonelle, campylobacter — INTERDIT en grossesse.'),
  f('LAIT PASTEURISE','Lait pasteurisé',S,'Pasteurisé — sûr. Source calcium et iode.'),
  f('LAIT UHT','Lait UHT (longue conservation)',S,'Stérilisé — très sûr.'),
  f('LAIT ENTIER','Lait entier',S,'Riche lipides et calcium — sûr.'),
  f('LAIT DEMI-ECREME','Lait demi-écrémé',S,'Sûr.'),
  f('LAIT ECREME','Lait écrémé',S,'Sûr.'),
  f('LAIT DE CHEVRE PASTEURISE','Lait de chèvre pasteurisé',S,'Pasteurisé — sûr.'),
  f('LAIT DE BREBIS PASTEURISE','Lait de brebis pasteurisé',S,'Pasteurisé — sûr.'),
  f('CREME FRAICHE PASTEURISEE','Crème fraîche pasteurisée',S,'Pasteurisée — sûr.'),
  f('BEURRE','Beurre',S,'Riche en vitamines A, D. Sûr.'),
  f('CREME DE BUREAU CRUE','Crème crue (fermière)',D,'Non pasteurisée — listériose. INTERDIT.'),
  f('YAOURT PASTEURISE','Yaourt/yoghourt pasteurisé',S,'Ferments lactiques — probiotiques. Très sûr.'),
  f('YAOURT AU BIFIDUS','Yaourt bifidus',S,'Probiotiques — recommandé grossesse.'),
  f('FROMAGE BLANC','Fromage blanc pasteurisé',S,'Frais pasteurisé — riche protéines. Sûr.'),
  f('FAISSELLE PASTEURISEE','Faisselle pasteurisée',S,'Fromage frais pasteurisé — sûr.'),
  f('CREME DESSERT','Crème dessert (pasteurisée)',S,'Pasteurisée — sûr.'),
  f('GLACE ARTISANALE','Glace artisanale (œufs crus)',C,'Œufs crus — risque salmonelle. Précaution.','medium'),
  f('GLACE INDUSTRIELLE','Glace industrielle (pasteurisée)',S,'Pasteurisée — sûr.'),
  f('LAIT RIBOT','Lait ribot (babeurre)',S,'Fermenté — pasteurisé. Sûr.'),
  f('LAITAGE FERMENTE','Lait fermenté (kéfir pasteurisé)',S,'Probiotiques — sûr.'),
  f('LAIT VEGETAL SOJA','Boisson au soja',C,'Phytooestrogènes — précaution si consommation massive.','medium'),
  f('LAIT VEGETAL AMANDE','Boisson amande',S,'Végétale — sûr (vérifier iode et calcium supplémentés).','medium'),
  f('LAIT VEGETAL AVOINE','Boisson avoine',S,'Végétale — sûr.'),
  f('LAIT VEGETAL RIZ','Boisson riz',S,'Végétale — pauvre en nutriments. Supplémentation conseillée.','medium'),
  f('LAIT VEGETAL NOIX DE COCO','Boisson noix de coco',S,'Végétale — sûr.'),
];

// ─── CÉRÉALES & LÉGUMINEUSES ──────────────────────────────────────────────
const GRAINS_LEGUMES: PreComputedIngredient[] = [
  f('BLE','Blé (farine, pain, pâtes)',S,'Céréale de base — sûr. Éviter excès gluten si sensibilité.'),
  f('RIZ BLANC','Riz blanc',S,'Céréale — sûr. Arsenic faible.','medium'),
  f('RIZ BRUN','Riz brun/complet',C,'Plus riche en arsenic que riz blanc — limiter à 1 portion/j.','medium'),
  f('RIZ SAUVAGE','Riz sauvage (wild rice)',S,'Sûr.'),
  f('AVOINE','Avoine (flocons, farine)',S,'Fibres bêta-glucane — sûr.'),
  f('ORGE','Orge',S,'Céréale fibreuse — sûr.'),
  f('SEIGLE','Seigle',S,'Céréale — sûr (attention ergot de seigle contaminé: DANGEREUX).','medium'),
  f('ERGOT DE SEIGLE','Ergot de seigle (contamination)',D,'Alcaloïdes ergot — abortif et vasoconstricteur. Danger contaminant.'),
  f('MAIS','Maïs',S,'Céréale — sûr. Pauvre en acide folique.'),
  f('MILLET','Millet',S,'Céréale sans gluten — sûr.'),
  f('SORGHO','Sorgho',S,'Céréale sans gluten — sûr.'),
  f('TEFF','Teff',S,'Céréale éthiopienne — sûr. Riche fer.'),
  f('FONIO','Fonio',S,'Céréale africaine — sûr.'),
  f('QUINOA','Quinoa (pseudo-céréale)',S,'Protéines complètes — sûr.'),
  f('AMARANTHE GRAIN','Amarante (graine)',S,'Pseudo-céréale riche protéines — sûr.'),
  f('SARRASIN','Sarrasin (blé noir)',S,'Sans gluten — rutine antioxydante. Sûr.'),
  f('EPEAUTRE','Épeautre (grand)',S,'Blé ancien — sûr.'),
  f('ENGRAIN','Engrain (petit épeautre)',S,'Blé ancestral pauvre gluten — sûr.'),
  f('LENTILLES','Lentilles (vertes, beluga, corail)',S,'Riches en fer, folates, protéines. Très recommandé grossesse.'),
  f('POIS CHICHES','Pois chiches',S,'Protéines végétales et folates. Sûr.'),
  f('HARICOTS NOIRS','Haricots noirs',S,'Protéines et fer. Sûr (bien cuire).'),
  f('HARICOTS ROUGES','Haricots rouges',S,'Bien cuits (lectines détruites à la cuisson). Sûr.'),
  f('HARICOTS CRUS','Haricots rouges crus',D,'Phasine — toxine détruite à la cuisson. INTERDIT cru.'),
  f('FÈVES','Fèves (Vicia faba)',C,'Favisme possible — précaution si déficit G6PD.','medium'),
  f('POIS VERTS','Petits pois',S,'Légumineuse fraîche — sûr.'),
  f('SOJA GRAIN','Soja (grain, tofu, tempeh)',C,'Phytooestrogènes — précaution si consommation excessive.','medium'),
  f('HARICOTS BLANCS','Haricots blancs',S,'Sûr — bien cuits.'),
  f('FLAGEOLETS','Flageolets',S,'Sûr.'),
  f('VESCES','Luzerne (alfalfa germes)',C,'Canavanine — précaution.','medium'),
  f('GERMES DE SOJA CRUS','Germes de soja crus',D,'Listériose et salmonelle — INTERDIT cru en grossesse.'),
  f('PÂTES ALIMENTAIRES','Pâtes alimentaires (cuites)',S,'Sûr.'),
  f('PAIN COMPLET','Pain complet (blé complet)',S,'Fibres et minéraux — recommandé.'),
  f('PAIN AUX CÉRÉALES','Pain multicéréales',S,'Sûr.'),
];

// ─── HUILES DE CUISSON & CORPS GRAS ──────────────────────────────────────
const COOKING_OILS: PreComputedIngredient[] = [
  f('HUILE D\'OLIVE','Huile d\'olive extra-vierge',S,'Oméga-9, vitamine E — recommandé. Résiste modérément à la chaleur.'),
  f('HUILE DE TOURNESOL','Huile de tournesol',S,'Oméga-6 — sûr.'),
  f('HUILE DE COLZA','Huile de colza',S,'Meilleur rapport oméga-3/6 — très recommandé grossesse.'),
  f('HUILE DE NOIX','Huile de noix',S,'Riche ALA oméga-3 — frais uniquement. Sûr.'),
  f('HUILE DE LIN','Huile de lin',S,'Très riche ALA — sûr, ne pas chauffer.'),
  f('HUILE DE NOISETTE','Huile de noisette',S,'Vitamine E — sûr.'),
  f('HUILE DE PEPIN DE RAISIN','Huile de pépins de raisin',S,'Point de fumée élevé — sûr.'),
  f('HUILE DE COCO VIERGE','Huile de coco vierge',S,'Acides gras moyen — sûr.'),
  f('HUILE D\'AVOCAT','Huile d\'avocat',S,'Point de fumée très élevé — sûr.'),
  f('HUILE DE SESAME','Huile de sésame',S,'Saveur prononcée — sûr.'),
  f('HUILE DE MAIS','Huile de maïs',S,'Oméga-6 — sûr.'),
  f('HUILE DE SOJA','Huile de soja',C,'Oméga-6 dominant, phytooestrogènes — modérer.','medium'),
  f('HUILE DE PALME','Huile de palme',S,'Acide palmitique — sûr. Problèmes environnementaux (non médical).','medium'),
  f('SAINDOUX','Saindoux (graisse de porc)',S,'Graisse animale saturée — sûr avec modération.','medium'),
  f('BEURRE DE CUISSON','Beurre (cuisson)',S,'Graisses saturées — sûr en quantité modérée.'),
  f('GHEE (BEURRE CLARIFIE)','Ghee (beurre clarifié)',S,'Lipides purs — sûr. Point de fumée élevé.'),
  f('MARGARINE','Margarine (végétale)',C,'Peut contenir acides gras trans — préférer beurre ou huile.','medium'),
  f('HUILE DE RIZ','Huile de son de riz',S,'Gamma-orizanol — sûr.'),
  f('HUILE DE CARTHAME','Huile de carthame',S,'Oméga-6 — sûr.'),
  f('HUILE DE CHANVRE','Huile de chanvre (alimentaire)',S,'Oméga-3/6 équilibrés — sûr.'),
  f('HUILE DE CAMELINE','Huile de cameline',S,'Riche ALA oméga-3 — recommandé.'),
  f('HUILE D\'ARGAN ALIMENTAIRE','Huile d\'argan (alimentaire)',S,'Oméga-9 et tocophérols — sûr.'),
];

// ─── CONDIMENTS & SAUCES ──────────────────────────────────────────────────
const CONDIMENTS: PreComputedIngredient[] = [
  f('MAYONNAISE MAISON','Mayonnaise maison (œuf cru)',D,'Œuf cru — salmonelle. INTERDIT.'),
  f('MAYONNAISE INDUSTRIELLE','Mayonnaise industrielle (pasteurisée)',S,'Pasteurisée — sûr.'),
  f('MOUTARDE','Moutarde',S,'Condiment — sûr aux doses usuelles.'),
  f('KETCHUP','Ketchup',S,'Tomate cuite — sûr. Attention sel et sucre.','medium'),
  f('VINAIGRE BALSAMIQUE','Vinaigre balsamique',S,'Acidité — sûr.'),
  f('VINAIGRE DE VIN','Vinaigre de vin',S,'Sûr.'),
  f('VINAIGRE DE CIDRE','Vinaigre de cidre',S,'Sûr aux doses alimentaires.'),
  f('SAUCE SOJA','Sauce soja (shodyu)',C,'Sel et phytooestrogènes soja — limiter la quantité.','medium'),
  f('SAUCE DE POISSON','Sauce nuoc-mâm/fish sauce',C,'Histamine et sel élevé — modérer.','medium'),
  f('SAUCE WORCESTERSHIRE','Sauce Worcestershire',C,'Anchoïs — précaution allergie et histamine. Sûr en petites doses.','medium'),
  f('SAUCE TABASCO','Tabasco (sauce piment)',S,'Épicé — sûr en quantité raisonnable.'),
  f('SAUCE SRIRACHA','Sriracha',S,'Sauce piment — sûr.'),
  f('SAUCE HOISIN','Sauce hoisin',S,'Sauce soja sucrée — sûr en modération.','medium'),
  f('HUILE PIMENTEE','Huile pimentée',S,'Sûr en petite quantité.'),
  f('CORNICHONS','Cornichons (vinaigre)',S,'Conserves acides — sûr.'),
  f('CÂPRES','Câpres',S,'Sûr.'),
  f('TAPENADE','Tapenade (anchoïs/olives)',S,'Sûr.'),
  f('HOUMOUS','Houmous (pois chiches)',S,'Protéines végétales — sûr.'),
  f('GUACAMOLE','Guacamole',S,'Avocat — sûr.'),
  f('PESTO BASILIC','Pesto basilic (pasteurisé)',S,'Pasteurisé — sûr. Artisanal: attention huile et fromage.','medium'),
  f('TZATZIKI','Tzatziki',S,'Yaourt et concombre — sûr si pasteurisé.'),
  f('SAUCE TARTARE','Sauce tartare',C,'Œufs — vérifier pasteurisation.','medium'),
  f('SAUCE BÉARNAISE MAISON','Sauce béarnaise maison',D,'Œufs partiellement cuits — risque salmonelle. INTERDIT maison.'),
  f('SAUCE HOLLANDAISE MAISON','Sauce hollandaise maison',D,'Œufs partiellement cuits — INTERDIT.'),
  f('SAUCE CAESAR MAISON','Sauce César maison (anchois, œuf)',D,'Œuf cru, anchois — INTERDIT.'),
  f('MISO','Miso (pâte fermentée)',C,'Phytooestrogènes soja, sel — modérer.','medium'),
  f('TAMARI','Tamari',C,'Soja — phytooestrogènes, sel. Modérer.','medium'),
  f('SIROP D\'ERABLE','Sirop d\'érable',S,'Sucre naturel — sûr avec modération.','medium'),
  f('MIEL (ADULTE)','Miel (adulte, grossesse)',S,'Sûr pour la mère. Ne jamais donner aux nourrissons.'),
  f('SUCRE','Sucre blanc/roux',S,'Sûr. Modération selon glycémie.','medium'),
  f('CONFITURE','Confiture/marmelade',S,'Sûr.'),
];

// ─── FRUITS SPÉCIFIQUES — NOTES GROSSESSE ─────────────────────────────────
const FRUITS_SPECIAL: PreComputedIngredient[] = [
  f('PAPAYE VERTE','Papaye verte non mûre',D,'Papaïne et latex — contractions utérines. INTERDIT.'),
  f('PAPAYE MURE','Papaye mûre',S,'Mûre et cuite — sûr. Vitamine C.'),
  f('ANANAS CRU EXCES','Ananas en grandes quantités',C,'Bromélaïne — utérotonique à hautes doses. En quantité raisonnable sûr.','medium'),
  f('ANANAS CUISINE','Ananas cuit (jus, conserve)',S,'Enzyme dénaturée par chaleur — sûr.'),
  f('RAISIN DE TABLE','Raisin (table)',S,'Sûr — riche en antioxydants.'),
  f('LITCHI','Litchi',C,'Méthylènecyclopropylglycine — précaution si à jeun/grandes quantités.','medium'),
  f('LONGANE','Longane',C,'Même famille litchi — précaution.','medium'),
  f('GRENADE','Grenade',S,'Antioxydants — sûr.'),
  f('FIGUE FRAICHE','Figue fraîche',S,'Sûr.'),
  f('KAKI','Kaki (plaqueminier)',S,'Sûr.'),
  f('GOYAVE','Goyave',S,'Vitamine C — sûr.'),
  f('MANGUE','Mangue',S,'Vitamines A/C — sûr.'),
  f('DURIAN','Durian',C,'Alcools sulfurés — précaution consommation excessive.','medium'),
  f('JACQUIER','Jacquier (jackfruit)',S,'Sûr.'),
  f('CARAMBOLE','Carambole',D,'Neurotoxine (acide carambolique) — INTERDITE aux insuffisants rénaux. Précaution grossesse.','medium'),
  f('NOIX DE COCO EAU','Eau de coco',S,'Hydratante et minéralisante — sûr.'),
  f('PLANTAIN','Plantain (banane plantain)',S,'Amidon — sûr.'),
  f('DATTIER (DATTES)','Dattes',S,'Riches sucres naturels — peuvent faciliter T3/travail. Sûr.','medium'),
  f('ABRICOT SEC','Abricot sec',S,'Fer naturel, fibres. Sûr.'),
  f('FIGUE SECHE','Figue sèche',S,'Calcium, fer. Sûr.'),
  f('PRUNEAU','Pruneaux',S,'Contre constipation grossesse — recommandé.'),
  f('RAISIN SEC','Raisin sec',S,'Énergie et fer — sûr.'),
  f('CRANBERRY FRAIS','Cranberry/canneberge',S,'Santé urinaire — recommandé grossesse (prévention cystite).'),
  f('GROSEILLE','Groseille',S,'Vitamine C — sûr.'),
  f('CASSIS','Cassis',S,'Anthocyanes — sûr.'),
  f('MYRTILLE FRAICHE','Myrtille fraîche',S,'Antioxydants — sûr.'),
  f('FRAISE FRAICHE','Fraise fraîche',S,'Vitamine C — sûr (bien laver).'),
  f('AGRUMES (ORANGE/CITRON)','Agrumes (orange, citron, pamplemousse)',S,'Vitamine C et folates. Sûr.'),
  f('PAMPLEMOUSSE (INTERACTION)','Pamplemousse (interactions médicaments)',C,'Inhibiteur CYP3A4 — peut modifier métabolisme médicaments. Vérifier avec médecin.','medium'),
];

// ─── ADDITIFS ALIMENTAIRES SUPPLÉMENTAIRES ─────────────────────────────────
const MORE_ADDITIVES: PreComputedIngredient[] = [
  f('E104 JAUNE QUINOLEINE','E104 — Jaune de quinoléine',C,'Colorant azoïque — hyperactivité enfant. Précaution grossesse.','medium'),
  f('E110 JAUNE ORANGE','E110 — Sunset yellow',C,'Azoïque — précaution grossesse.','medium'),
  f('E122 CARMOISINE','E122 — Carmoisine/Azorubine',C,'Colorant azoïque — précaution.','medium'),
  f('E123 AMARANTE ROUGE','E123 — Amarante',D,'Colorant — interdit USA et URSS. Précaution forte.','medium'),
  f('E124 PONCEAU 4R','E124 — Rouge cochenille A',C,'Azoïque — précaution grossesse.','medium'),
  f('E131 BLEU PATENTE','E131 — Bleu patenté V',C,'Colorant synthétique — précaution.','medium'),
  f('E132 INDIGO CARMIN','E132 — Bleu indigo',C,'Allergie possible — précaution.','medium'),
  f('E133 BLEU BRILLANT','E133 — Bleu brillant FCF',C,'Précaution — données limitées grossesse.','medium'),
  f('E150A CARAMEL','E150a — Caramel simple',S,'Colorant naturel — sûr.'),
  f('E150D CARAMEL AMMONIAC','E150d — Caramel au sulfite ammoniac',C,'Ammoniaque — précaution.','medium'),
  f('E160A CAROTENES','E160a — Carotènes',S,'Colorant naturel (carotte) — sûr.'),
  f('E160B ANNATTO','E160b — Annato/bixine',C,'Colorant naturel — allergie possible. Précaution.','medium'),
  f('E171 DIOXYDE DE TITANE','E171 — Dioxyde de titane (nano)',D,'Nanoparticules — INTERDIT dans alimentation UE depuis 2022. Précaution.'),
  f('E172 OXYDES DE FER ALIM','E172 — Oxydes de fer alimentaires',S,'Colorants minéraux — sûr.'),
  f('E211 BENZOATE DE SODIUM','E211 — Benzoate de sodium',C,'Conservateur — hyperactivité enfant, précaution grossesse.','medium'),
  f('E212 BENZOATE DE POTASSIUM','E212 — Benzoate de potassium',C,'Conservateur — précaution.','medium'),
  f('E213 BENZOATE DE CALCIUM','E213 — Benzoate de calcium',C,'Conservateur — précaution.','medium'),
  f('E220 SO2 SULFITES','E220-E228 — Dioxyde de soufre / Sulfites',C,'Allergène déclaré — asthme, précaution grossesse en grande quantité.','medium'),
  f('E249 NITRITE POTASSIUM','E249 — Nitrite de potassium',D,'Charcuterie — méthémoglobinémie, nitrosamines. ÉVITER en grossesse.'),
  f('E250 NITRITE SODIUM','E250 — Nitrite de sodium',D,'Conservateur charcuterie — précaution forte, nitrosamines cancérogènes.'),
  f('E251 NITRATE SODIUM','E251 — Nitrate de sodium',D,'Converti en nitrite — ÉVITER.'),
  f('E252 NITRATE POTASSIUM','E252 — Nitrate de potassium',D,'Salpêtre — même problème nitrites. ÉVITER.'),
  f('E310-E320 GALLATES','E310-E312 Gallates — antioxydants',C,'Précaution allergies. Précaution grossesse.','medium'),
  f('E321 BHT','E321 — BHT (hydroxytoluène butylé)',C,'Antioxydant — perturbateur endocrinien potentiel. Précaution.','medium'),
  f('E407 CARRAGHENANE','E407 — Carraghénane',C,'Épaississant algue — inflammation intestinale possible. Précaution grossesse.','medium'),
  f('E415 GOMME XANTHANE','E415 — Gomme xanthane',S,'Épaississant naturel — sûr.'),
  f('E420 SORBITOL ALIM','E420 — Sorbitol alimentaire',S,'Édulcorant — transit. Sûr.'),
  f('E422 GLYCEROL ALIM','E422 — Glycérol',S,'Humectant — sûr.'),
  f('E450-E452 POLYPHOSPHATES','E450-E452 — Polyphosphates',C,'Chélateur calcium — précaution excès grossesse.','medium'),
  f('E471 MONO-DIGLYCÉRIDES','E471 — Mono et diglycérides d\'acides gras',S,'Émulsifiant naturel — sûr.'),
  f('E476 PGPR','E476 — Ester polyricinolique polyglycérol',S,'Émulsifiant chocolat — sûr.','medium'),
  f('E481 STÉAROYL LACTYLATE','E481 — Stéaroyl-2-lactylate de sodium',S,'Émulsifiant — sûr.'),
  f('E500 BICARBONATE SOUDE','E500 — Bicarbonate de sodium',S,'Levure chimique — sûr.'),
  f('E503 CARBONATE AMMONIUM','E503 — Carbonate d\'ammonium',S,'Agent levant — sûr.'),
  f('E504 CARBONATE MAGNESIUM','E504 — Carbonate de magnésium',S,'Antiagglomérant — sûr.'),
  f('E621 GLUTAMATE SODIUM (MSG)','E621 — Glutamate monosodique (MSG)',S,'Exhausteur de goût — sûr aux doses habituelles.','medium'),
  f('E627 GUANYLATE DISODIQUE','E627 — Guanylate disodique',C,'Dérivé nucléotide — précaution si goutte. Sûr en général.','medium'),
  f('E631 INOSINATE DISODIQUE','E631 — Inosinate disodique',C,'Exhausteur — précaution si goutte.','medium'),
  f('E900 DIMETHYLPOLYSILOXANE','E900 — Diméthylpolysiloxane',S,'Antimoussant — sûr.'),
  f('E904 SHELLAC','E904 — Shellac',S,'Résine naturelle — enrobage. Sûr.'),
  f('E920 CYSTEINE L','E920 — Cystéine L',S,'Amélorant farine — acide aminé naturel. Sûr.'),
  f('E927B CARBAMIDE UREE','E927b — Carbamide (urée)',S,'Agent de traitement — sûr.'),
  f('E950 ACESULFAME K','E950 — Acésulfame K',C,'Édulcorant — données insuffisantes grossesse. Précaution.','medium'),
  f('E951 ASPARTAME','E951 — Aspartame',C,'Phénylalanine — CI si phénylcétonurie. Données grossesse limitées. Précaution.','medium'),
  f('E952 CYCLAMATE','E952 — Cyclamate',D,'Interdit dans de nombreux pays. DÉCONSEILLÉ.'),
  f('E954 SACCHARINE','E954 — Saccharine',D,'Passe barrière placentaire — DÉCONSEILLÉ grossesse.'),
  f('E955 SUCRALOSE','E955 — Sucralose',C,'Édulcorant — données limitées. Précaution.','medium'),
  f('E959 NEOHESPERIDINE','E959 — Néohespéridine DC',C,'Édulcorant — précaution données.','medium'),
  f('E960 STEVIOL GLYCOSIDE','E960 — Glycosides de stéviol (stévia)',S,'Édulcorant naturel — données encourageantes. Sûr.','medium'),
  f('E961 NEOTAME','E961 — Néotame',C,'Aspartame modifié — précaution.','medium'),
  f('E962 SEL ASPARTAME','E962 — Sel d\'aspartame-acésulfame',C,'Combinaison — précaution.','medium'),
  f('E965 MALTITOL','E965 — Maltitol',S,'Polyol — sûr.'),
  f('E966 LACTITOL','E966 — Lactitol',S,'Polyol — sûr.'),
  f('E967 XYLITOL ALIM','E967 — Xylitol alimentaire',S,'Polyol naturel — sûr (attention excès transit).'),
  f('E968 ERYTHRITOL ALIM','E968 — Érythritol alimentaire',S,'Polyol — très bien toléré. Sûr.'),
];

export async function scrapeEFSA(): Promise<PreComputedIngredient[]> {
  return [
    ...COLORANTS, ...PRESERVATIVES, ...ANTIOXIDANTS, ...THICKENERS,
    ...FLAVOR_ENHANCERS, ...SWEETENERS, ...PROCESSING_AIDS,
    ...INFECTION_RISKS, ...MERCURY_FISH, ...CAFFEINE_SOURCES,
    ...ALCOHOL, ...VITAMINS_MINERALS, ...HERBS_FOOD, ...FATS, ...POLLUTANTS,
    // Nouvelles sections
    ...CHEESES, ...FISH_SPECIES, ...MEAT_TYPES, ...HERBS_SPICES_2,
    ...TEAS_INFUSIONS, ...NUTS_SEEDS, ...DAIRY_PRODUCTS, ...GRAINS_LEGUMES,
    ...COOKING_OILS, ...CONDIMENTS, ...FRUITS_SPECIAL, ...MORE_ADDITIVES,
  ];
}
