// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AppStoreScreenshots.tsx": () => import("../components/mockups/AppStoreScreenshots.tsx"),
  "./components/mockups/RestaurantMode/RestaurantMode.tsx": () => import("../components/mockups/RestaurantMode/RestaurantMode.tsx")
};
